### ISSUE TITLE
🚀 [Feature] remember last filter set

### ISSUE THREAD

**Issue by Tirokk** [Ocelot-Social-Community/Ocelot-Social#1908]
> [<img alt="hermann-san" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/hermann-san) **Authored by [hermann-san](https://github.com/hermann-san)**
_<time datetime="2019-10-15T19:10:26Z" title="Tuesday, October 15th 2019, 9:10:26 pm +02:00">Oct 15, 2019</time>_

---

## :rocket: Feature
There are categories that I'm not interested at all. Never. E.g. Economy and Finance or Health.
It would be nice if HC would remember which categories I've selected the last time I was logged in and pre-select those when I log-in the next day.

![image](https://user-images.githubusercontent.com/7679654/66862190-b905b980-ef90-11e9-9b74-cedc51546020.png)

**Comment by ulfgebhardt** [comment]
Since we simplify the filter alot we can close this I beleive
