### ISSUE TITLE
🚀 [Feature] Show supported image formats in editor

### ISSUE THREAD

**Issue by Tirokk** [Ocelot-Social-Community/Ocelot-Social#1949]
> [<img alt="datenbrei" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/datenbrei) **Authored by [datenbrei](https://github.com/datenbrei)**
_<time datetime="2019-10-18T06:28:51Z" title="Friday, October 18th 2019, 8:28:51 am +02:00">Oct 18, 2019</time>_

---

## :rocket: Feature
It would be selfexplaining, if the supported image formats would show of in the editor, as long as there is no image added. This way it would be selfexplaining what formats are supported

### Design & Layout
![bildformate](https://user-images.githubusercontent.com/13457963/67070751-2bd58700-f181-11e9-9a67-9452992bc93f.png)

**Comment by dasari810** [comment]
@Tirokk  I'am interested to work on this issue .

**Comment by Tirokk** [comment]
Hey @dasari810 ,

would be cool if you work in this feature. Thanks for your interest! 🤗💫
If you need any help, please let me know.

I invited you to this repository as volunteer via an e-mail invitation you can accept.
After you accepted, please clone this repo (don’t fork) push your feature branch directly to this repo and create a PR using master as the base branch.

I assigned you to this issue …

Our conversation runs over our discord channels:
https://discord.com/invite/DFSjPaX

On Discord we have kind of every day a Daily Standup at UTC 10:30 am (CET 11:30 am) in the Conference Room or we message a link in the coding channel.

**Comment by dasari810** [comment]
@Tirokk i accepted the invite , thanks for that .. and i will start working on this isuues .

**Comment by Tirokk** [comment]
Wonderful! @dasari810

**Comment by dasari810** [comment]
@Tirokk  want to suggestions from you before making a pr :

-  is the text content  and style ok  : 

![Screenshot from 2020-10-26 00-11-49](https://user-images.githubusercontent.com/64162781/97116013-7ee10300-1720-11eb-9e5e-b4d0fb46f2b4.png)

**Comment by Tirokk** [comment]
Yes this looks good to me @dasari810 ! 👍🏼🤗

**Comment by dasari810** [comment]
@Tirokk  what about showing the text in different languages ?

**Comment by Tirokk** [comment]
@dasari810 english is the base language. German should be there as well and a german can prove it on the review process.
Okay?

**Comment by dasari810** [comment]
> @dasari810 english is the base language. German should be there as well and a german can prove it on the review process.
> Okay?

**Comment by dasari810** [comment]
fine , i have translated it into all the languages listed in the site :+1:
