### ISSUE TITLE
🚀 [Feature] Filter contributions by location

### ISSUE THREAD

**Issue by Tirokk** [Ocelot-Social-Community/Ocelot-Social#266]
> [<img alt="sushidave" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/sushidave) **Authored by [sushidave](https://github.com/sushidave)**
_<time datetime="2018-12-17T19:02:58Z" title="Monday, December 17th 2018, 8:02:58 pm +01:00">Dec 17, 2018</time>_

---

**Is your feature request related to a problem? Please describe.**
Some contributions are about national, regional or local things only. Currently, there is no efficient way to search/filter for contributions by location. The only way is to use the search field and hope for results. The more users and contributions on the network the stronger the need for such a feature.

**Describe the solution you'd like**
- An optional location field for contributions featuring the same data fields as in #44
- An option to filter (out) contributions by location

**Additional context**

Example: 
A contribution about something local in Papua New Guinea will hardly be relevant for someone in Germany. The filter by location function helps people to take action on things within their region and enables them to better connect with each other in real life.

**Comment by Tirokk** [comment]
> [<img alt="appinteractive" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/appinteractive) **Authored by [appinteractive](https://github.com/appinteractive)**
_<time datetime="2018-12-17T22:05:34Z" title="Monday, December 17th 2018, 11:05:34 pm +01:00">Dec 17, 2018</time>_

---


Related to #9

**Comment by Tirokk** [comment]
> [<img alt="sushidave" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/sushidave) **Authored by [sushidave](https://github.com/sushidave)**
_<time datetime="2019-01-05T11:07:41Z" title="Saturday, January 5th 2019, 12:07:41 pm +01:00">Jan 5, 2019</time>_

---


This feature is vital for users for local interaction. Please compare with https://www.communecter.org/, section "Are you ready for geo-communication?", how they did it.

**Comment by Tirokk** [comment]
> [<img alt="appinteractive" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/appinteractive) **Authored by [appinteractive](https://github.com/appinteractive)**
_<time datetime="2019-01-05T15:45:19Z" title="Saturday, January 5th 2019, 4:45:19 pm +01:00">Jan 5, 2019</time>_

---


I don’t get „how they did it“ can you explain or summarize here what the did in a good way and why?

**Comment by Tirokk** [comment]
> [<img alt="sushidave" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/sushidave) **Authored by [sushidave](https://github.com/sushidave)**
_<time datetime="2019-01-05T18:59:11Z" title="Saturday, January 5th 2019, 7:59:11 pm +01:00">Jan 5, 2019</time>_

---


Of course...sorry for my brevity. 

Communecter states that it "invites users to geo-locate your data as much as possible to give local visibility to your actions.". 

Currently on Communecter, you can filter contributions by location by category ("theme") and tags:
![communecter-search-theme](https://user-images.githubusercontent.com/17728384/50728111-21338f00-1125-11e9-8473-4ae01ad9f678.png)

... and by type:
![communecter-search-type](https://user-images.githubusercontent.com/17728384/50728113-285a9d00-1125-11e9-8896-641f170bb936.png)

(screenshots from https://www.communecter.org/#search.)

Their contribution form provides input fields for geo location data, see:
![grafik](https://user-images.githubusercontent.com/17728384/50727776-0874aa80-1120-11e9-81cb-7df1f76d594b.png)

I guess HC plans geo-location for users, organisations, events and projects, so I imagine this could be easily applied to regular posts as an optional attribute. 

It enables users to search/filter also for posts based on their area of living/interest.

Btw, Communecter's search engine looks quite powerful.

**Comment by Tirokk** [comment]
> [<img alt="mattwr18" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/mattwr18) **Authored by [mattwr18](https://github.com/mattwr18)**
_<time datetime="2019-11-20T18:17:39Z" title="Wednesday, November 20th 2019, 7:17:39 pm +01:00">Nov 20, 2019</time>_

---


related to https://github.com/Human-Connection/Human-Connection/issues/782
I think there is a sense that this would be important for some users/the network, so I'd say lets leave this open and discuss it more

**Comment by Tirokk** [comment]
> [<img alt="Tirokk" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/Tirokk) **Authored by [Tirokk](https://github.com/Tirokk)**
_<time datetime="2019-12-09T09:16:02Z" title="Monday, December 9th 2019, 10:16:02 am +01:00">Dec 9, 2019</time>_

---


My impression is that this can be a little bit different than #782 , but don’t have to be in general:

- Local can mean a perimeter, because it can be related to a distance.
  - For meeting people not more than 10 or 20 kilometres away, as an example.
  - Find people or projects in the neighbourhood.
  - Or is related to a little village or a city.

- Local can mean it is not world wide and has no clear perimeter as a nation in a sense of a political system of a country as well. Germany or the EU as an example.

The second point is clearly meant in #782 @mattwr18 and probably here as well.
The first point can be even a bit different to the one here discussed.

**Comment by sushidave** [comment]
@Tirokk 
If the location relates to the content of the post only a part of the posts can have a geo location. Thus the location data input should be optional.
Posts with location data can be filtered. They could be displayed on a map, too.

**Comment by Tirokk** [comment]
not needed at the moment
