### ISSUE TITLE
🐛 [Bug] Runtime error [Vue warn]: Invalid component name

### ISSUE THREAD

**Issue by Tirokk** [Ocelot-Social-Community/Ocelot-Social#2749]
> [<img alt="mattwr18" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/mattwr18) **Authored by [mattwr18](https://github.com/mattwr18)**
_<time datetime="2020-01-13T12:46:22Z" title="Monday, January 13th 2020, 1:46:22 pm +01:00">Jan 13, 2020</time>_

---

## :bug: Bugreport

[Vue warn]: Invalid component name: "pages/profile/_id.vue". Component names should conform to valid custom element name in html5 specification.

### Steps to reproduce the behavior
1. go to profile page
2. open dev console
3. see if the error is present, if not, try refreshing the page
4. doesn't always appear
5. Profit

can be related to this issue https://github.com/nuxt/nuxt.js/issues/165

**Comment by mahula** [comment]
The reported behavior cannot be reproduced.

**Comment by Tirokk** [comment]
Should be solved. Otherwise I would have seen it in the last years.
