### ISSUE TITLE
🐛 [Bug] Sometimes notifications are not marked as read

### ISSUE THREAD

**Issue by Tirokk** [Ocelot-Social-Community/Ocelot-Social#2821]
> [<img alt="sushidave" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/sushidave) **Authored by [sushidave](https://github.com/sushidave)**
_<time datetime="2020-01-17T11:24:06Z" title="Friday, January 17th 2020, 12:24:06 pm +01:00">Jan 17, 2020</time>_

---

## :bug: Bugreport

Sometimes notifications are not marked as "read" although the user clicked on the notification preview and the counter doesn't change.

### Steps to reproduce the behavior
1. Click on the bell.
2. Click on the notification preview. Sometimes it's not marked as read and the counter doesn't change.
3. Reload the page in order to update the read status and counter.

### Expected behavior

A click on the notification preview always marks it as read and updates the counter.

### Version & Environment
 Type: [Notebook]      
 - OS: [macOS]      
 - Browser: [Firefox] 
 - Version [72.0.1]  
 - Device: [MacBook]

**Comment by Tirokk** [comment]
> [<img alt="Elweyn" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/Elweyn) **Authored by [Elweyn](https://github.com/Elweyn)**
_<time datetime="2020-08-06T09:28:12Z" title="Thursday, August 6th 2020, 11:28:12 am +02:00">Aug 6, 2020</time>_

---


Maybe merge this issue with #3357 cause I think they have both to change the same code part. (In my opinion)

**Comment by Tirokk** [comment]
> [<img alt="Elweyn" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/Elweyn) **Authored by [Elweyn](https://github.com/Elweyn)**
_<time datetime="2020-08-06T14:26:58Z" title="Thursday, August 6th 2020, 4:26:58 pm +02:00">Aug 6, 2020</time>_

---


Oh I have read the ticket again and now I am not so sure if it is related to the bug described in #2112 will need to check this issue more in detail...
Could not reproduce the described behavior

**Comment by ulfgebhardt** [comment]
seems no longer to b happening
