### ISSUE TITLE
🚀[Feature] Feed: Show number of search results

### ISSUE THREAD

**Issue by Tirokk** [Ocelot-Social-Community/Ocelot-Social#295]
> [<img alt="sushidave" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/sushidave) **Authored by [sushidave](https://github.com/sushidave)**
_<time datetime="2019-03-10T14:46:39Z" title="Sunday, March 10th 2019, 3:46:39 pm +01:00">Mar 10, 2019</time>_

---

**Is your feature request related to a problem? Please describe.**
When contibutions are filtered or searched there is no indication of the number of hits (= of contributions found) except if there are none.

**Describe the solution you'd like**
Show the number of hits on the feed page.

Is solved by #3271

**Comment by sushidave** [comment]
Good morning @Tirokk  
@stomobe would like to work on this issue (see [here](https://github.com/Human-Connection/Human-Connection/issues/295)). Please provide him with all necessary information.
Cheers!

**Comment by Mogge** [comment]
Welcome. This issue is related to a bigger PR, which is already in progress. If you want, we can meet and take a look at an issue that fits better.

**Comment by stomobe** [comment]
Hello @Mogge  
Firstly, thank you for the offer. I would be eager to work on a better-fitting issue. Is there a method of communication and time that would be convenient for you to discuss? I went ahead and joined the Discord server as well, in case. I will also continue looking through the list for an appropriate issue on my own in the meanwhile!

**Comment by Mogge** [comment]
@stomobe give me a ping on discord. Or introduce yourself in the coding voice chat and I will reach out for you.

**Comment by Tirokk** [comment]
Hey @stomobe ,
did you have had already contact with us or @Mogge on Discord?

**Comment by stomobe** [comment]
Hello @Tirokk,
Yes, Mogge reached out to me and we were able to converse. My understanding is that this issue is already part of a pull request, so I was starting to assist on a different issue, #3738 . But currently, I have been preparing for final exams and have not made progress yet other than examining the Vue file in the backend.  

Thank you for the invite! And my Discord name is "Cipher." :)
