### ISSUE TITLE
🐛 [Bug] comment box disappears while editing comments

### ISSUE THREAD

**Issue by Tirokk** [Ocelot-Social-Community/Ocelot-Social#3015]
> [<img alt="tidus9" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/tidus9) **Authored by [tidus9](https://github.com/tidus9)**
_<time datetime="2020-02-06T14:14:20Z" title="Thursday, February 6th 2020, 3:14:20 pm +01:00">Feb 6, 2020</time>_

---

## :bug: Bugreport
When you edit a comment, the comment box at the bottom disappears and displays this text:

"Commenting is not possible at this time on this post.
This can happen for several reasons, please see our FAQ"

### Expected behavior
The comment box shouldn't disappear while you editing a comment in the same post.

### Additional context
![image](https://user-images.githubusercontent.com/51242288/73944679-43cd4400-48f3-11ea-9e38-46c1dea0f06b.png)

**Comment by Tirokk** [comment]
As far I know this problem doesn’t exist anymore. Or?
@ulfgebhardt @Mogge @sushidave

**Comment by sushidave** [comment]
@Tirokk 
I don't know.
Does that text appear if the user has been blocked by the author of the post?
Are blocked users permitted to edit their existing comments?

**Comment by Tirokk** [comment]
I will try this out after my holidays … @sushidave

**Comment by sushidave** [comment]
@Tirokk and I verified the issue and found out that it works as designed. A blocked user can still edit or delete his/her existing comments but not create a new one. Closing this issue.
