### ISSUE TITLE
🚀 [Feature] Avoid the color red for non-essential things

### ISSUE THREAD

**Issue by Tirokk** [Ocelot-Social-Community/Ocelot-Social#3086]
> [<img alt="alina-beck" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/alina-beck) **Authored by [alina-beck](https://github.com/alina-beck)**
_<time datetime="2020-02-17T16:15:05Z" title="Monday, February 17th 2020, 5:15:05 pm +01:00">Feb 17, 2020</time>_

---

## :rocket: Feature
requested by @DennisHack 

Red should be used very sparingly on the network – and only to focus our users' attention on the really important things, like charitable actions.

### User Problem

Users are distracted and their attention is guided towards the wrong details, due to our use of colors. Especially the notifications in the header should not be red as they are not as important as other features on the network.

#### Create Post

<img width="770" alt="Bildschirmfoto 2023-03-27 um 15 29 03" src="https://user-images.githubusercontent.com/25344101/227995405-1358be68-ad75-4d81-a5ef-b62cbbf5cc5e.png">

### Implementation

1. go through the code/network and see where the color red is used
2. decide if it should be used in those locations (it is ok for destructive actions, like deleting a user account)
3. replace it with an alternative color – preferably green

### Design & Layout
See examples in our [clickdummy](https://preview.uxpin.com/24a2ab8adcd84f9a763d87ed27251351225e0ecd#/pages/99768901/simulate/sitemap?mode=i)

### Validation
Users will focus less on notifications.

**Comment by Tirokk** [comment]
> [<img alt="Ruben80" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/Ruben80) **Authored by [Ruben80](https://github.com/Ruben80)**
_<time datetime="2020-02-21T18:39:16Z" title="Friday, February 21st 2020, 7:39:16 pm +01:00">Feb 21, 2020</time>_

---


Hi, Can I help on this issue?

**Comment by Tirokk** [comment]
Where is this still relevant @sushidave ?
Or can we close it?

**Comment by sushidave** [comment]
@Tirokk
It's still relevant here:

- [ ]  Cancel button on create post page

...and might be here too:

- [ ] New notifications counter in the header
