### ISSUE TITLE
🐛 [Bug] Post options too small

### ISSUE THREAD

**Issue by Tirokk** [Ocelot-Social-Community/Ocelot-Social#3186]
> [<img alt="hermann-san" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/hermann-san) **Authored by [hermann-san](https://github.com/hermann-san)**
_<time datetime="2020-02-29T20:07:01Z" title="Saturday, February 29th 2020, 9:07:01 pm +01:00">Feb 29, 2020</time>_

---

## :bug: Bugreport

Button to modify an existing post is IMHO too small relative to other buttons and text

### Steps to reproduce the behavior
1.  create a post
2.   Open the post and  check the button
Profit  :  It's easier to find the button when it has been made bigger

### Expected behavior
Button should be easy to spot

### Version & Environment
 Type:   Desktop
 - OS: Linux Mint 19
 - Browser: Firefox 73 + Chromium latest
 - Device: PC

### Additional context

![image](https://user-images.githubusercontent.com/7679654/75614063-e6fd2c00-5b34-11ea-8d16-5e723d83bc9e.png)

**Comment by Tirokk** [comment]
> [<img alt="sushidave" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/sushidave) **Authored by [sushidave](https://github.com/sushidave)**
_<time datetime="2020-06-17T15:50:09Z" title="Wednesday, June 17th 2020, 5:50:09 pm +02:00">Jun 17, 2020</time>_

---


@hermann-san How about turning the three dots into a burger bar (= three horizontal lines) as this is a common symbol for a navigation menu?

**Comment by Tirokk** [comment]
> [<img alt="sushidave" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/sushidave) **Authored by [sushidave](https://github.com/sushidave)**
_<time datetime="2020-06-17T16:09:01Z" title="Wednesday, June 17th 2020, 6:09:01 pm +02:00">Jun 17, 2020</time>_

---


This button is used for other menus too, like for comments and on the user profile page. So it needs to be changed for all those places.

**Comment by Tirokk** [comment]
> [<img alt="hermann-san" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/hermann-san) **Authored by [hermann-san](https://github.com/hermann-san)**
_<time datetime="2020-06-20T23:30:02Z" title="Sunday, June 21st 2020, 1:30:02 am +02:00">Jun 21, 2020</time>_

---


I'm not a developer, but these are just my observations.
On Android,  3 bars are typically used on the top, left corner. I assume this is a Android app design guideline. Also I've seen the 3 dots on the top right corner.  even here on Git (desktop browser) I can see the 3 dots on the right hand side of each comment.
Making the 3 dot's simply thicker would do, from my point of view. 
Alternative could be making a circle around them, or alike - but I'd prefer simply more thickness.

**Comment by sushidave** [comment]
Hi @Tirokk , 
Please see @KarthickSakthi 's comment at https://github.com/Human-Connection/Human-Connection/issues/3186 and provide him with further details so that he can work on this issue. Thank you!

**Comment by Tirokk** [comment]
This issue will be solved by my PR https://github.com/Ocelot-Social-Community/Ocelot-Social/pull/5132/files#diff-8584acfaa0db1146f82b41c1a63c7879653f89f41ab2af76a2565fdf50be1e4b by removing the `ghost`option on the button, when the groups branch there `5059-epic-groups` will be merged into the `master`.

@KarthickSakthi so I will close this issue …

**Comment by Tirokk** [comment]
Hey @KarthickSakthi ,

please chose an other issue.

I cared for your invitation to our community as volunteer via an e-mail invitation you can accept.

Our conversation runs over our discord server:
https://discord.gg/AJSX9DCSUA
There we have usually from Monday to Thursday a Daily Standup at UTC 09:30 am (CEST 11:30 am) in the Office Cube.

Please don’t compare from your fork to this repository, in case, because the publish GitHub Action will fail, because of permission problems with the credentials.
Just push your branch directly to our repo and compare to the master.
If you accept the invitation then you’ll have the right todo so. 😉

**Comment by KarthickSakthi** [comment]
@Tirokk @sushidave Thanks for your responses, Actually I thought it's a reactjs based project. But it's not. So I can't able to start. You can assign  issues to other, who's were looking for!.
Thank you!

**Comment by Tirokk** [comment]
Hey @KarthickSakthi ,

thanks for let knowing us.
If there comes a time if you like to program or learn VueJS, please let us know.
Have a nice time!

**Comment by sushidave** [comment]
@KarthickSakthi Thanks for your feedback also from my side. 

I was checking our list of other open source social networks in GitHub if one of them uses ReactJS, but the ones I found ([Vue-Mini-Social-Network](https://github.com/yTakkar/Vue-Mini-Social-Network) and [React Social Network](https://github.com/red-gold/react-social-network) seem to be no longer active... So I hope you'll soon find another project that uses ReactJS where you can use your creativity.

Thanks again for your interest and hope to see you again.
Take care!
