### ISSUE TITLE
🐛 [Bug] Migrate undeleted comments of Anonymous users from Alpha to Nitro

### ISSUE THREAD

**Issue by Tirokk** [Ocelot-Social-Community/Ocelot-Social#3321]
> [<img alt="sushidave" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/sushidave) **Authored by [sushidave](https://github.com/sushidave)**
_<time datetime="2020-03-23T12:44:10Z" title="Monday, March 23rd 2020, 1:44:10 pm +01:00">Mar 23, 2020</time>_

---

## :bug: Bugreport

On 20th September 2019, user _hannelore_at_ reported that the comments of her deleted account from the Alpha version are missing in the Nitro version although she had chosen not to have her contents deleted.

Example of post with missing comments:
https://human-connection.social/post/5c7a539e71d6940092b2cf1a/art-2-der-menschenrechte-verbot-der-diskriminierung
At least the first comment is missing.

@datenbrei replied that in the Alpha version:
- the user decided if the contributions should stay.
- the process aborted due to bugs but the contents were flagged as NOT TO BE DELETED.
- we [the network provider] deleted the data except the flagged ones.

...and that at time of migration the comments of possibly ALL anonymous users were fallen by the wayside.

### Expected behavior

All contents of anonymous users who chose to keep their contents in the system should appear in Nitro.

### Version & Environment
any

### Additional context

If it's not possible or too much effort to migrate the missing contents of all affected users then please recreate or provide those comments of user hannelore_at in the posts tagged as "AEMR": https://human-connection.social/?hashtag=AEMR

As discussed with @roschaefer

**Comment by ulfgebhardt** [comment]
no longer applies
