### ISSUE TITLE
🐛 [Bug] Wrong German umlaut handling for usernames at account creation

### ISSUE THREAD

**Issue by Tirokk** [Ocelot-Social-Community/Ocelot-Social#3504]
> [<img alt="sushidave" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/sushidave) **Authored by [sushidave](https://github.com/sushidave)**
_<time datetime="2020-04-25T17:35:28Z" title="Saturday, April 25th 2020, 7:35:28 pm +02:00">Apr 25, 2020</time>_

---

## :bug: Bugreport

At account creation, usernames are not encoded correctly if the profile name contains one or more German umlauts:
Ä/ä -> a
Ö/ö -> o
Ü/ü -> u

Examples:
- Sandra Märtens -> sandra-martens
- Oliver Stöckel -> oliver-stockel
- Günter Hürst -> gunter-hurst

### Steps to reproduce the behavior
1. Create a new account using one or more German umlauts in the profile name.
2. Check the username.

### Expected behavior

German umlauts should be encoded like this:
Ä/ä -> ae
Ö/ö -> oe
Ü/ü -> ue

Examples:
- Sandra Märtens -> sandra-maertens
- Oliver Stöckel -> oliver-stoeckel
- Günter Hürst -> guenter-huerst

### Version & Environment
 Type: [any]      
 - OS: [any]      
 - Browser: [any] 
 - Version [any]  
 - Device: [any]

**Comment by Tirokk** [comment]
> [<img alt="ATOMktn" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/ATOMktn) **Authored by [ATOMktn](https://github.com/ATOMktn)**
_<time datetime="2020-06-18T15:20:17Z" title="Thursday, June 18th 2020, 5:20:17 pm +02:00">Jun 18, 2020</time>_

---


Hi! I'm new to open source and would like to take a crack at this!

**Comment by Tirokk** [comment]
> [<img alt="sushidave" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/sushidave) **Authored by [sushidave](https://github.com/sushidave)**
_<time datetime="2020-06-18T17:00:00Z" title="Thursday, June 18th 2020, 7:00:00 pm +02:00">Jun 18, 2020</time>_

---


Hello @ATOMktn and welcome on board! Thank you for your interest in this project. @Tirokk Please provide ATOMktn with further info. Thanks!

**Comment by Tirokk** [comment]
> [<img alt="Tirokk" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/Tirokk) **Authored by [Tirokk](https://github.com/Tirokk)**
_<time datetime="2020-06-22T08:06:42Z" title="Monday, June 22nd 2020, 10:06:42 am +02:00">Jun 22, 2020</time>_

---


Hello @ATOMktn ,

I have invited you to our repository as volunteer via an e-mail invitation you can except.
After you excepted, please push your feature branch directly to this repo and create a PR using master as the base branch.

I assigned you to this issue …

Our conversation runs over our discord channels:
http://hc.world/discord
Another possibility to get to there:
https://discord.com/invite/DFSjPaX

On Discord we have kind of every day a Daily Standup at UTC 09:30 am (CEST 11:30 am) in the Conference Room.

**Comment by ulfgebhardt** [comment]
https://github.com/ocelot-social-community/ocelot-social/issues/3676

**Comment by Brandon-G-Tripp** [comment]
@Tirokk Hey Wolle. I want to discuss taking on this issue. In discord you said we should chat about how to go about this. I have the app up and running again. Somehow it got corrupted and I was missing some modules so I cloned the app down again.

**Comment by Tirokk** [comment]
Hey @Brandon-G-Tripp ,

we have already the PR #3676 for this issue done by @ATOMktn.
But for me this solution was too specific for German to me.

I would like to have a very general `regex` solution for all languages and all characters. I mean a regex where every non ANSII characters gets converted to an ANSII string.

Have a quick investigation and If you don’t find anything, please let me know. I think I have seen a solution last year somewhere.

**Comment by Brandon-G-Tripp** [comment]
@Tirokk I found some ways of replacing all the diacritics in the characters with their standard keyboard equivalent but not the changing of ü -> ue and so on. I will take a look at @ATOMktn pull request and see if I can combine them so we have to correct handling of the umlaut and then just remove the diacritics for other languages.

**Comment by Tirokk** [comment]
I have investigated a bit and couldn’t find what I meant to have seen.
Yeah, just have a table of umlaut etc. (Unicode) characters to replace and delete the rest or replace them by underlines or dashes. @Brandon-G-Tripp 👍🏼

**Comment by Brandon-G-Tripp** [comment]
@Tirokk  Hey I see that the previous work on this issue was just doing a charmap for the characters. Would you prefer this in regex or should I just expand the work there?

**Comment by Mogge** [comment]
I have this post title `Tösting ße ßlüg ççç ñññ ÄÖÜ` and I get the slug: `tosting-sse-sslug-ccc-nnn-aou`
