### ISSUE TITLE
🚀 [Feature] Display favicons for social media links and redesign link box on profile page

### ISSUE THREAD

**Issue by Tirokk** [Ocelot-Social-Community/Ocelot-Social#3505]
> [<img alt="sushidave" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/sushidave) **Authored by [sushidave](https://github.com/sushidave)**
_<time datetime="2020-04-25T18:22:22Z" title="Saturday, April 25th 2020, 8:22:22 pm +02:00">Apr 25, 2020</time>_

---

## :rocket: Feature

Display the favicons of social media links on the user profile page and redesign link (smaller icon, text next to icon).

### User Problem

1.) Currently, a standard icon is displayed for all social media links on the user profile page. This makes it hard for users to recognise the social media network instantly, especially for the larger networks. However, the respective favicon for each link is displayed on the social media page in the account settings.
2.) The link icon is too large and takes up too much space of the link box.

### Implementation

1.) If there is a favicon, display it instead of the standard icon.
2.) Smaller icon size (same as avatar icon in the followers box) and put text next to it.

### Design & Layout

![hc-favicons-on-profile-page](https://user-images.githubusercontent.com/17728384/80290029-18fcca00-8743-11ea-8bf0-7e611ef139f5.jpg)

(left: social media page in the account settings | right: links box on the profile page)

**Comment by Tirokk** [comment]
> [<img alt="klaffert" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/klaffert) **Authored by [klaffert](https://github.com/klaffert)**
_<time datetime="2020-05-04T21:19:42Z" title="Monday, May 4th 2020, 11:19:42 pm +02:00">May 4, 2020</time>_

---


@sushidave Is this still open? If so, I'd like to take it on!

**Comment by Tirokk** [comment]
> [<img alt="sushidave" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/sushidave) **Authored by [sushidave](https://github.com/sushidave)**
_<time datetime="2020-05-04T22:09:05Z" title="Tuesday, May 5th 2020, 12:09:05 am +02:00">May 5, 2020</time>_

---


@klaffert Hi Kelliann! Greetings to Seattle and thank you for your readiness to contribute to this project. I think this issue is still open. @Tirokk could you please advise Kelliann if she can give it a go?

**Comment by Tirokk** [comment]
> [<img alt="Mogge" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/Mogge) **Authored by [Mogge](https://github.com/Mogge)**
_<time datetime="2020-05-07T10:50:56Z" title="Thursday, May 7th 2020, 12:50:56 pm +02:00">May 7, 2020</time>_

---


@klaffert you are very welcome to work on this issue. Please get in touch with us on discord:
https://discord.com/channels/489522408076738561/497575439657599006

**Comment by Tirokk** [comment]
> [<img alt="Tirokk" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/Tirokk) **Authored by [Tirokk](https://github.com/Tirokk)**
_<time datetime="2020-05-07T10:54:56Z" title="Thursday, May 7th 2020, 12:54:56 pm +02:00">May 7, 2020</time>_

---


Hello @klaffert , nice you want to take this one over.

I assigned you to this issue.

Please don’t push from a fork. This leads to failing Travis builds.
I send you an invitation to this repo via mail so that you are able to pull and push directly to this repo.

Our conversation runs over our discord channels like @Mogge just wrote. 👆🏼
http://hc.world/discord
… is another possibility to get to it. Or:
https://discord.com/invite/DFSjPaX

**Comment by Tirokk** [comment]
> [<img alt="JonCanales" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/JonCanales) **Authored by [JonCanales](https://github.com/JonCanales)**
_<time datetime="2020-05-28T02:39:36Z" title="Thursday, May 28th 2020, 4:39:36 am +02:00">May 28, 2020</time>_

---


Is this still open?

**Comment by Tirokk** [comment]
> [<img alt="Tirokk" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/Tirokk) **Authored by [Tirokk](https://github.com/Tirokk)**
_<time datetime="2020-05-28T07:47:25Z" title="Thursday, May 28th 2020, 9:47:25 am +02:00">May 28, 2020</time>_

---


This is still open @JonCanales !

Will you go for it?. 💫

In case I have invited you to our repository as volunteer via an e-mail invitation you can except.
After you excepted, please push your feature branch directly to this repo and create a PR using master as the base branch.

I assigned you to this issue …

Our conversation runs over our discord channels:
http://hc.world/discord
Another possibility to get to it:
https://discord.com/invite/DFSjPaX

**Comment by Tirokk** [comment]
> [<img alt="sushidave" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/sushidave) **Authored by [sushidave](https://github.com/sushidave)**
_<time datetime="2020-05-28T12:33:51Z" title="Thursday, May 28th 2020, 2:33:51 pm +02:00">May 28, 2020</time>_

---


@Tirokk Before @JonCanales starts on this issue I have a basic question about data privacy:
I assume that every time a settings page or profile page is called, some personal data is sent to those external websites that host the favicons. In order to better protect user's privacy and minimize data traffic wouldn't it be smarter to abstain from displaying favicons of external websites but just show the link?

**Comment by Tirokk** [comment]
> [<img alt="Tirokk" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/Tirokk) **Authored by [Tirokk](https://github.com/Tirokk)**
_<time datetime="2020-05-28T14:16:39Z" title="Thursday, May 28th 2020, 4:16:39 pm +02:00">May 28, 2020</time>_

---


With a favicon the link looks much better. @sushidave 🤔

We can ask if this may have privacy indications. I don’t know for now.

@roschaefer has this any privacy issues so far.
If yes may we can cache the favicons for a while? Or any other ideas?

**Comment by Tirokk** [comment]
> [<img alt="roschaefer" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/roschaefer) **Authored by [roschaefer](https://github.com/roschaefer)**
_<time datetime="2020-05-29T20:10:05Z" title="Friday, May 29th 2020, 10:10:05 pm +02:00">May 29, 2020</time>_

---


In general it might be possible that a mere request of the favicon already exposes data, that's correct. However, there is no ID on the request.

But anyways, if you want to be 100% sure there is no data exposed, how about using the backend as a proxy server to the favicon? Or download the favicon in the backend when you save a social media link?

**Comment by Mogge** [comment]
It would be good to have a component for the social media selection. For now it is in the page, but we also want to use the functionality for organizations.
