### ISSUE TITLE
🚀 [Feature] Legend of post editor toolbar buttons

### ISSUE THREAD

**Issue by Tirokk** [Ocelot-Social-Community/Ocelot-Social#3673]
> [<img alt="sushidave" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/sushidave) **Authored by [sushidave](https://github.com/sushidave)**
_<time datetime="2020-06-24T13:44:57Z" title="Wednesday, June 24th 2020, 3:44:57 pm +02:00">Jun 24, 2020</time>_

---

## :rocket: Feature

In the user interface, show a legend of the functions and markdown of the buttons of the post editor toolbar.

The tooltip shall be displayed if the mouse pointer hovers over the question mark icon next to the toolbar. On touchscreens the tooltip shall be triggered by "touch".

The text is similar to the list in this [FAQ](https://support.human-connection.org/kb/faq.php?id=52&lang=en_US). 

The text is localised so it matches the language that the user selected.

### User Problem

Many users don't understand the meaning of the icons of the toolbar. Also, they don't know about markdown (unless they check the FAQ) which would enable them to write posts more efficiently. The legend solves that problem by being provided directly within the network.

### Implementation

- [x] Add a round button with a question mark next to the toolbar. Use the existing one of the login page.
- [x] Add the functionality to the button to show/hide the tooltip. It should be displayed if the mouse pointer hovers over it. On touchscreens the tooltip should be triggered by "touch".
- [x] Add a tooltip with localised content from lokalize.co.
- [x] Make it responsive for touch devices.

### Design & Layout

![hc-legend-of-editor-toolbar-buttons](https://user-images.githubusercontent.com/17728384/85565859-cbf87f80-b62f-11ea-8fa3-13874116f241.png)

### Validation

Users write posts more efficiently. They spend less time on the network and more offline. Less support effort.

### Additional context

This feature complements the tooltips of single buttons, see issue #1950. It can be implemented independantly.
This feature is part of the initiative to improve the post editor, see epic feature #3625 .

**Comment by Brandon-G-Tripp** [comment]
Hey @Tirokk this looks like it would be a good issue to start on if no one else has taken it.

**Comment by Tirokk** [comment]
Hey @Brandon-G-Tripp ,

Thanks for your interest! 🤗💫
This one looks good for me as well.

I invited you to this repository as volunteer via an e-mail invitation you can accept.
After you accepted, please clone this repo (don’t fork) – I know you have already done – push your feature branch directly to this repo and create a PR using master as the base branch.

I assign you then to this issue …

See you in our pairing session at UTC 8am (CET 1pm). 🤗

PS: On Discord we have kind of every day a Daily Standup at UTC 09:30 am (CEST 11:30 am) in the Conference Room or we message a link in the coding channel.

**Comment by Blargian** [comment]
@Tirokk Hi, is someone still working on this issue? I'm keen to get involved as a first timer.

**Comment by Tirokk** [comment]
@Blargian ,

since @Brandon-G-Tripp is not reacting I assign you to this issue.

**Comment by Tirokk** [comment]
@Blargian ,
@Brandon-G-Tripp has agreed to overhand this issue to you.

**Comment by Blargian** [comment]
Hey everyone, I've started working on this finally. I've created a "Menu Legend" component, added the question mark icon. Currently the legend displays when hovering over the icon as shown below. I am just having one small problem with the css in that the legend gets hidden. The basecard component which forms the editor menu and editor content area has an overflow hidden property so the legend component gets hidden. 

I wondered if someone maybe had some advice for how to best handle that? I thought to maybe render the component from further up in the component tree but this makes it harder to align the component to the question mark icon. 

![image](https://user-images.githubusercontent.com/41984034/122647166-17e6e300-d123-11eb-8a57-9cac3a00fd62.png)

**Comment by Tirokk** [comment]
Hey @Blargian ,

that looks nice. 😍
Thanks for your effort!

It would be cool 😎 if you would also push pull requests in progress into our repository. If you do that, we can see upfront what the state of your work is @Blargian and can give you tips. Especially when it comes to solving programming problems like you mentioned.

I wonder if you could find some useful examples in the editors link menu or in the context menus of posts and comments which are as well placed on base-cards:

<img width="1627" alt="Bildschirmfoto 2021-06-21 um 15 20 08" src="https://user-images.githubusercontent.com/25344101/122768760-33c5c280-d2a4-11eb-8f34-2cc6b1f55ba3.png">

<img width="1627" alt="Bildschirmfoto 2021-06-21 um 15 16 51" src="https://user-images.githubusercontent.com/25344101/122768444-e21d3800-d2a3-11eb-82f8-005a8a6ea586.png">

<img width="1627" alt="Bildschirmfoto 2021-06-21 um 15 13 30" src="https://user-images.githubusercontent.com/25344101/122768491-ed706380-d2a3-11eb-956c-d6b150cafadc.png">

<img width="1627" alt="Bildschirmfoto 2021-06-21 um 15 13 08" src="https://user-images.githubusercontent.com/25344101/122768512-f4977180-d2a3-11eb-88c2-4ab8868caa3a.png">

**Comment by Blargian** [comment]
Thanks @Tirokk for the feedback and suggestions, they helped! I've opened a WIP pull request for what I have so far. It's not much at the moment, just a basic component. I'm totally new to Vue so I'm moving at a bit of a snails pace 😅

**Comment by Tirokk** [comment]
Top!😍
I wrote you on the issue directly @Blargian …

**Comment by Tirokk** [comment]
I reopen this, because there is a console warning in the browser and also by running the webapp tests I and @Blargian have overseen:

<img width="1515" alt="Bildschirmfoto 2021-07-20 um 11 58 12" src="https://user-images.githubusercontent.com/25344101/126304987-626acd9d-ed99-4ef1-b3e5-67361ae396aa.png">

**Comment by Tirokk** [comment]
Forgot to reopen …

**Comment by sushidave** [comment]
@blargian @Tirokk @Mogge @Brandon-G-Tripp 
Hey everyone. I just realised this feature has been implemented and you made it happen. Thanks a lot to all of you!
