### ISSUE TITLE
🚀 [Feature] Show capslock icon on password fields

### ISSUE THREAD

**Issue by Tirokk** [Ocelot-Social-Community/Ocelot-Social#3779]
> [<img alt="sushidave" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/sushidave) **Authored by [sushidave](https://github.com/sushidave)**
_<time datetime="2020-08-05T11:10:36Z" title="Wednesday, August 5th 2020, 1:10:36 pm +02:00">Aug 5, 2020</time>_

---

## :rocket: Feature

A capslock icon should appear in password fields left to the show/hide button if the capslock key is active.

### User Problem

Currently, the UI doesn't support users getting aware of their capslock key being active and that the login or changing a password might fail. This feature:
- Provides a better user experience and satisfaction
- Increases the rate of successful logins and change of passwords
- Reduces system load

### Implementation

- Add a capslock icon to the login form that responds to the capslock key
- Add it to other password fields of the network.

### Design & Layout

![show-capslock-icon-on-login-form](https://user-images.githubusercontent.com/17728384/89404516-6c0af380-d71a-11ea-99fe-34fbad71879e.png)

### Validation

- Better user experience and satisfaction
- Reduced system load

### Additional context

This feature can be implemented separately from #2434 which solves a similar problem.

**Comment by Tirokk** [comment]
> [<img alt="enigmatic241" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/enigmatic241) **Authored by [enigmatic241](https://github.com/enigmatic241)**
_<time datetime="2020-08-24T05:50:36Z" title="Monday, August 24th 2020, 7:50:36 am +02:00">Aug 24, 2020</time>_

---


@sushidave I want to work on this.

**Comment by Tirokk** [comment]
> [<img alt="sushidave" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/sushidave) **Authored by [sushidave](https://github.com/sushidave)**
_<time datetime="2020-08-24T13:23:58Z" title="Monday, August 24th 2020, 3:23:58 pm +02:00">Aug 24, 2020</time>_

---


Hello @enigmatic241 and greetings to India! Many thanks for your message and your readiness to work on this issue. I'm asking @Tirokk to provide you with the necessary details. He'll be back to work this week and supporting you if you need any help.

**Comment by Tirokk** [comment]
> [<img alt="enigmatic241" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/enigmatic241) **Authored by [enigmatic241](https://github.com/enigmatic241)**
_<time datetime="2020-08-26T04:38:06Z" title="Wednesday, August 26th 2020, 6:38:06 am +02:00">Aug 26, 2020</time>_

---


Thank you @sushidave , when will @Tirokk provides me the necessary details ?

**Comment by Tirokk** [comment]
> [<img alt="Tirokk" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/Tirokk) **Authored by [Tirokk](https://github.com/Tirokk)**
_<time datetime="2020-08-26T08:59:56Z" title="Wednesday, August 26th 2020, 10:59:56 am +02:00">Aug 26, 2020</time>_

---


Hey @enigmatic241 , I will provide you with the necessary details.

**Comment by Tirokk** [comment]
> [<img alt="Tirokk" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/Tirokk) **Authored by [Tirokk](https://github.com/Tirokk)**
_<time datetime="2020-08-26T09:05:38Z" title="Wednesday, August 26th 2020, 11:05:38 am +02:00">Aug 26, 2020</time>_

---


May you could care for issue #2434 as well? @enigmatic241

**Comment by Tirokk** [comment]
> [<img alt="enigmatic241" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/enigmatic241) **Authored by [enigmatic241](https://github.com/enigmatic241)**
_<time datetime="2020-08-26T13:47:13Z" title="Wednesday, August 26th 2020, 3:47:13 pm +02:00">Aug 26, 2020</time>_

---


Thanks @Tirokk.  I have gone through the issue #2434 and discussion which was available their, please brief me how do I contribute and in case of any help, I will get back to you.

**Comment by Tirokk** [comment]
> [<img alt="Tirokk" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/Tirokk) **Authored by [Tirokk](https://github.com/Tirokk)**
_<time datetime="2020-08-27T17:01:44Z" title="Thursday, August 27th 2020, 7:01:44 pm +02:00">Aug 27, 2020</time>_

---


Hello @enigmatic241 ,

I cared for your invitation to our repository as volunteer via an e-mail invitation you can accept.
After you accept, please clone this repo (don’t fork) **push your feature branch directly to this repo and create a PR using master** as the base branch.

I assigned you to this issue …

Our conversation runs over our discord channels:
http://hc.world/discord
Another possibility to get to there:
https://discord.com/invite/DFSjPaX

On Discord we have kind of every day a Daily Standup at UTC 09:30 am (CEST 11:30 am) in the Conference Room.

PS: I and we will be not available till Monday.

**Comment by Brandon-G-Tripp** [comment]
@Tirokk Hey I am looking at this issue and I see there is a question icon in the password input. It does not seem to be doing any functionality. Can I replace with the caps and hide password icon?

**Comment by Tirokk** [comment]
Yes @Brandon-G-Tripp ,
good catch! 🙏🏼
You can replace it. 👍🏼

**Comment by Mogge** [comment]
I am not sure that it is the best solution to place another icon in the input field to indicate that capslock is avtive. I think a warning message under the input field is much better. So we do not overload out input component with another icon.

**Comment by Mogge** [comment]
We decided not to work on this issue for now. We have a good solution wit the show password feature to help users with password problems. I anyone finds a good solution feel welcome to give it a try, but it has very low priority right now. See some possible solution here: #4031

**Comment by ulfgebhardt** [comment]
Closing this then - thanks for the effort <3
