### ISSUE TITLE
🚀 [Feature] Make my-social-media to a Component

### ISSUE THREAD

**Issue by Tirokk** [Ocelot-Social-Community/Ocelot-Social#3813]
> [<img alt="ogerly" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/ogerly) **Authored by [ogerly](https://github.com/ogerly)**
_<time datetime="2020-08-20T12:06:52Z" title="Thursday, August 20th 2020, 2:06:52 pm +02:00">Aug 20, 2020</time>_

---

## :rocket: Feature
Make my-social-media to a Component

### User Problem
Currently the my-social-media is used as a page in the profile area of a user.
Since we also want to use it in other places in the system, it should be converted to a component,
which can be used everywhere in other forms without problems.
the next example is the categorieSelect component.

### Implementation
webapp/pages/settings/my-social-media.vue soll to component pleace :)

**Comment by Tirokk** [comment]
@nimitbhargava is this related to the PR #4047 you are working on?

**Comment by nimitbhargava** [comment]
@Tirokk Yes it's similar to my [PR](https://github.com/Ocelot-Social-Community/Ocelot-Social/pull/4047)
Although the naming of my component is different from the one suggested in this issue.

I will refactor the naming of the component and it's location as expected in this issue.

**Comment by nimitbhargava** [comment]
Yes, this is related to #4047 (fix social media icons and moving the implementation to componenet at user page) but this page is for settings. I will pick this up.

**Comment by Tirokk** [comment]
Not jet

**Comment by Tirokk** [comment]
We don't need it at the moment.
