### ISSUE TITLE
💬 [Question] Alternatives for MapBox? 

### ISSUE THREAD

**Issue by Tirokk** [Ocelot-Social-Community/Ocelot-Social#3833]
> [<img alt="Mogge" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/Mogge) **Authored by [Mogge](https://github.com/Mogge)**
_<time datetime="2020-08-27T09:41:52Z" title="Thursday, August 27th 2020, 11:41:52 am +02:00">Aug 27, 2020</time>_

---

## :speech_balloon: Question

We are using MapBox for the Geolocation of Users. There are issues with the change of data received from MapBox. The IDs changed, which leads to dublicates of Locations in our database and the tests to fail. The names of Locations change, which leads out tests to fail.

Further, as far as I know, it is not possible to add addresses, which could be interesting for the organizations.

What alternatives do we have?

**Comment by hermann-san** [comment]
maybe [Leaflet](https://leafletjs.com/)?  #35

**Comment by Tirokk** [comment]
@emily876 commented on this issue at HC on this issue https://github.com/Human-Connection/Human-Connection/issues/3833#issuecomment-882105541 :

> You can use Google maps API but I guess it's paid one. Other options can be, open street map, arc GIS..

**Comment by Tirokk** [comment]
Hey @emily876 ,

we probably prefer Open Street Map over Google Maps, because we love open source, and don’t like to pay much to a big tech company.

Are you interested in implementing Open Street Map or in investigation of other opportunities?

**Comment by emily876** [comment]
Yea.. I'm trying to understand the code base and looking for issues on which I can work!

**Comment by Tirokk** [comment]
If you you have questions or need help @emily876 , please let me know.

**Comment by emily876** [comment]
Yeah sure , thank you very much !!

**Comment by Tirokk** [comment]
@appinteractive says he would prefer MapBox over other incl. Open Street Map, because MapBox relays on Open Street Map as well, but has the much better options to display everything in modern styles.

**Comment by Tirokk** [comment]
@Mogge can we close this for now.
It's still relevant kind of, but at the moment we stick to MabBox. Or?
