### ISSUE TITLE
🐛 [Bug] post gets created even if the user uploads unsupported file formats

### ISSUE THREAD

**Issue by dasari810** [Ocelot-Social-Community/Ocelot-Social#3923]
while creating post if the user uploads image of format other than supported ( jpg/png/gif) the post gets created and the post appears as : 

![Screenshot from 2020-10-26 01-00-53](https://user-images.githubusercontent.com/64162781/97116970-eb5f0080-1726-11eb-8960-677d041522b8.png)

### Steps to reproduce the behavior
1. create  a  new post 
2. upload a image of file format other that ( jpg/png/gif)
3. click the confirm button 
4. now check the created post 

### Expected behavior

the post should not get created or warn ( or just inform the user ) about the supported file formats

### Version & Environment
 Type: [ Desktop ]      
 - OS: [ubuntu ]      
 - Browser: [ chrome 85.0.4183.83 ] 
 - Version [ ]  
 - Device: []  

### Additional context

 I think this issue can be resolved if user is restricted to upload only supported file formats , like .. when the user clicks the upload button only the supported file formats are filtered from users device ( as we do it in html by ```accept="image/*"```  for the file input field)

**Comment by ftonato** [comment]
```javascript
const fileInput = document.getElementById('file');
const filePath = fileInput.value;


const isAllowedUpload = (filePath, extensions) => {
  return allowedExtensions.exec(filePath);
}
if(!isAllowedUpload(filePath, allowedExtensions)){
  // NOT ALLOWED
  // showErrorMessage
  // Please upload file having extensions .jpeg/.jpg/.png/.gif only.
}

// ALLOWED
```

**Comment by dasari810** [comment]
yes , @ftonato  that's a great solution  , but i think it's better to restrict the user before uploading than evaluating it after upload ( it can be easily done by adding a property to input feilds )

**Comment by dasari810** [comment]
@Tirokk shall i start working on this issue ?

**Comment by Tirokk** [comment]
Hey @dasari810 ,
yes, for sure !

Thanks for caring and creating this one! 🤗👍🏼

PS: Thanks @ftonato for spending your thinking in this one as well! 🍀

**Comment by ftonato** [comment]
Hey guys,

Yeah, @dasari810 You're completely right, I was only sending a small example of how deal with the problem, but of course, make more sense to "validate" after the upload happened or during (`@change/@input` events of the `<input />`.

My point was: "Please, create a logic to validate, not only adding `accept="image/*"` on the input, because the user can easily manipulate this."

**Comment by dasari810** [comment]
Hey @ftonato  i didn't think of that , thanks for letting me know :blush:
i  will definitely implement it ...
