### ISSUE TITLE
🐛 [Bug] No Text Appears For Categories In Italian Language

### ISSUE THREAD

**Issue by Tirokk** [Ocelot-Social-Community/Ocelot-Social#3929]
## :bug: Bugreport

There is now text translation appearing for the categories on post creation in Italian language.

<img width="1876" alt="Bildschirmfoto 2020-10-27 um 08 27 27" src="https://user-images.githubusercontent.com/25344101/97271404-cce52c00-1830-11eb-9760-a8b523d4a956.png">

### Steps to reproduce the behavior

1. go to the newsfeed
2. click `+` for the creation of a post
3. see not translation text on the categories

### Expected behavior

There should be a translation or english language should show up as default.

### Version & Environment
 Type: Desktop      
 - OS: macOS      
 - Browser: FireFox 
 - Version []  
 - Device: []  

### Additional context

None

**Comment by dasari810** [comment]
even the placeholders of title , select Language fields  and text of cancel button are also not shown

**Comment by Tirokk** [comment]
Correct @dasari810 .
That’s a real pity!

**Comment by Tirokk** [comment]
This seems to be fixed after I tested!
