### ISSUE TITLE
💬 [Question] Who will be the author of the code?

### ISSUE THREAD

**Issue by Mogge** [Ocelot-Social-Community/Ocelot-Social#3940]
## :speech_balloon: Question

In `backend/package.json` and `frontend/package.json` was Human Connection gGmbH indicated as author. Which organization do we want to use now as author?

**Comment by Tirokk** [comment]
May we could use this issue to collect reminders of the white-labelling? @Mogge

**Comment by Tirokk** [comment]
This is already solved and changed.
