### ISSUE TITLE
💬 [Question] Remove unused Discord Channels

### ISSUE THREAD

**Issue by ulfgebhardt** [Ocelot-Social-Community/Ocelot-Social#4020]
## :speech_balloon: Question

Remove unused Discord Channels

![Bildschirmfoto 2020-12-01 um 10.52.09.png](https://images.zenhubusercontent.com/5c2df999aae337748ba526e9/6a3b030e-7fe2-4658-8799-4fe1349a94be)

![image](https://user-images.githubusercontent.com/1238238/100447026-1df67300-30b0-11eb-8237-a32a5af44735.png)

### Removed

- [ ] github
- [X] ssh

**Comment by Tirokk** [comment]
The `github`channel could be useful to find out the GitHub names of our team at least.
The people sometimes don’t know whom to mention on GitHub to reach a specific dev from here.
But the need is discussable for sure.

**Comment by Tirokk** [comment]
The channels under `Newsfeed` can be discussed as well.

**Comment by ulfgebhardt** [comment]
Done
