### ISSUE TITLE
💥 [DevOps] Create A GitBook From Our Readme's

### ISSUE THREAD

**Issue by Tirokk** [Ocelot-Social-Community/Ocelot-Social#4021]
## :fire: DevOps ticket

On Human Connection we have https://docs.human-connection.org/human-connection/
We should setup this instructions for ocelot.social.

### Motive

Have own docs.
Be independent.

### Related issues

None

### Implementation

To find out.
May ask @roschaefer ?

### Validation

None

### Additional context

None

**Comment by mahula** [comment]
With the implementation of the vuepress-based https://docs.ocelot.social/ we fullfilled this task.
