### ISSUE TITLE
💥 [DevOps] Setup A New Digital Ocean Cluster

### ISSUE THREAD

**Issue by Tirokk** [Ocelot-Social-Community/Ocelot-Social#4043]
## :fire: DevOps ticket

Setup a new digital ocean cluster.

### Motive

Have a new running network with real users.

### Related issues

Related issue #4010 .

### Implementation

I will find out.

### Validation

None

### Additional context

None

**Comment by ulfgebhardt** [comment]
Is this done @Tirokk ? Whats the exact scope of the issue?

**Comment by Tirokk** [comment]
Yeah, that’s true @ulfgebhardt .
I’ve obviously forgot the write that this issue is fixed by my PR you mentioned instead of writing
 relates …
