### ISSUE TITLE
💥 [DevOps] Latest Node Version Is Not Working In The Builds

### ISSUE THREAD

**Issue by Tirokk** [Ocelot-Social-Community/Ocelot-Social#4048]
## :fire: DevOps ticket

We like to use the latest Node version in the Docker files for the builds of the webapp, backend, and maintenance, like it was earlier.

```dockerfiles
FROM node:lts-alpine as base
```

As a quick solution we fixed this with a fixed old Node version:

```dockerfiles
FROM node:12.19.0-alpine3.10 as base
```

### Motive

Latest node version is not working in the builds. See above. 👆🏼

### Related issues

Commit: https://github.com/Ocelot-Social-Community/Ocelot-Social/commit/b6fe5483ccde8c752108e44603ebb39c3a2b508c
Commit: https://github.com/Ocelot-Social-Community/Ocelot-Social/commit/844da649f07348c8737e709bb53a53abbd4041f7

### Implementation

To investigate.

### Validation

See if the PR and master builds running …

### Additional context

As we got a Node bump https://github.com/Ocelot-Social-Community/Ocelot-Social/commit/b6fe5483ccde8c752108e44603ebb39c3a2b508c to:

```dockerfiles
FROM node:15.3.0-alpine3.10 as base
```

The error while build the webapp was:

```
error /develop-webapp/node_modules/node-sass: Command failed.
```

@Mogge please fill in here what the reason was. (Something about Python calls …)

**Comment by Mogge** [comment]
For some reason node-sass need python to compile. At least this is what the error says. Can we provide python to the image?

**Comment by Tirokk** [comment]
We have to find out. I don’t know how to do yet @Mogge .

**Comment by Mogge** [comment]
see #4082
can we close this @Tirokk ?
