### ISSUE TITLE
🔧 [Refactor] Unify all installation instructions in Readme

### ISSUE THREAD

**Issue by ulfgebhardt** [Ocelot-Social-Community/Ocelot-Social#4049]
## :zap: Refactor ticket

Unify all installation instructions in Readme
-> The documentation is scattered all over the place
-> The documentation is partly still on human connection
-> Everything must go into the `README.md` file or another md file in the repository linked from the readme.

**Comment by Tirokk** [comment]
I don’t think that documentation is scattered all over the place. May I’m mistaken?

We used GitBook at HC to have it collected which worked fine for me:
https://docs.human-connection.org/human-connection/

We have to setup GitBook at our `Ocelot-Social`repository as we did at HC. There’s this issue #XXX about it

**Comment by ulfgebhardt** [comment]
i would love to remove that dependency - move everything to github.
There is no need for external tools on this matter.

If we move from HC to somewhere - the somewhere could be Github, so in the future there is no need to move anythign anymore. Documentation and code are in the same location.

Where are the installation instructions on github? Are they available somewhere or do I need to use the gitbook?

**Comment by ulfgebhardt** [comment]
Maybe this is  viable option: https://medium.com/@richdayandnight/simple-tutorial-on-hosting-your-gitbook-documentation-on-github-pages-bonus-with-gitbook-editor-f27f60d5d408

**Comment by Tirokk** [comment]
What you pointed out is a possible option. 👆🏼

It’s kind of similar as what we had at HC I guess, but we have to figure out.
It as well works with the `SUMMRY.md` we have already in our main folder and which we used with GitBook at HC.

The goal is:

- to have a book with all the well structured docs and at the same time have the same docs in the related folders where devs search usually for them
- and perfect would be to have also a link on each readme to the structured book
- and in the structured book to the related folder on GitHub where the code lives

**Comment by ulfgebhardt** [comment]
This is partly already done or on the way. We greed to remove gitbook specific syntax and stuff gets unified step by step
