### ISSUE TITLE
🌟 [EPIC] 1.1.0 - Deployment & Donations

### ISSUE THREAD

**Issue by ulfgebhardt** [Ocelot-Social-Community/Ocelot-Social#4053]
### 1.1.0 - Deployment & Donations

- [x] Deployment & Rebranding
- [x] Donation Bar

**Comment by Tirokk** [comment]
I guess, we can close this? @ulfgebhardt

**Comment by Tirokk** [comment]
This was fulfilled at version 1.0.5
