### ISSUE TITLE
🐛 [Bug] Image upload is not working in local development environment

### ISSUE THREAD

**Issue by Mogge** [Ocelot-Social-Community/Ocelot-Social#4081]
## :bug: Bugreport
When setting up the local dev env without docker, the image upload is not working.
Error message: `GraphQL error: a ReadStream cannot be created from a destroyed WriteStream`.
The cropping of images is not working as well.
When using docker, everything is working fine.

### Steps to reproduce the behavior
1. Create a new post
2. Fill in all necessary fields 
3. Upload an image, crop it and click on confirm
4. Save the post

### Expected behavior
The image should be saved in the `backend/public/uploads` folder. A success message should be toasted.

### Version & Environment
Local development without docker on current master. I tried earlier versions back to 2 months and the same problem occurs. I tried the behavior on the master of the HC repository and the same error occurs. So it has nothing to do with the cloning.

### Additional context
file: `backend/src/schema/resolvers/images/images.js`
The promise in line 115 provokes the error.

**Comment by Mogge** [comment]
Further examination:
 * In node 12.19.0 as used by docker saving and cropping of images works fine.
 * To switch between node versions locally I recommend https://dev.to/bornfightcompany/switching-between-multiple-node-versions-with-node-version-manager-1jb6

**Comment by Mogge** [comment]
This leads me to the conclusion that updating our node version is no good idea until this  is fixed.

**Comment by Tirokk** [comment]
This is solved by PR #4083 I understand right? @Mogge

**Comment by Mogge** [comment]
I do not know how to treat this best. We can close it, but it is realted to #4082 . May be we reopen it, when we really want to upgrade our node version.
