### ISSUE TITLE
💬 [Question] Categories - why we don't need them ;)

### ISSUE THREAD

**Issue by ulfgebhardt** [Ocelot-Social-Community/Ocelot-Social#4120]
## :speech_balloon: Question

As you all know, I have trouble with the Concept Categories. I think we will have to undergo a decision about how to approch it soon. Therefore I want to advocate my request to remove them here(again) in length:

**What are Categories used for**

1. Display Icons on the Post, including a Tooltip with the Category name on the post (card and post page)
2. Filter by Categories
3. The user is obligated to choose at least one Category when creating a Post, but a maximum of three

That is all they do as far as I know.

**Whats the problem, can't you just shove it already?**

4. The Implementation is according to @Mogge suboptimal, making it very hard to change the existing Categories or make them dynamic in any form
5. The admin has to define the Categories(once he could do that properly) - its not the user who defines them - therefore Categories are very static - the admin might not guess correctly what Categories the Community needs.
6. Translations have to be handled and is a lot of work assuming you have several languages
7. The use is very limited as stated above

**What is your suggestion?**

I believe we should replace categories completely by Tags. A Tag fulfills everything a Category does except the limits (it is very unpractical to define a maximum of Tags per Post like it is currently with Categories)
A Tagsystem would enable to do the following:
1. Display Icons on a Post if certain Tags are present
2. Filter by a certain amount (admin defined / most used / any other metric) of Tags 
3. We could force the user to choose at least one of the admin defined Tags for his post, a maximum would be unpractical but could be done on the admin defined Tags
4. The Tags would be dynamic by default since they are user defined
5. The admin can analyse the Tags used by the community to define useful filters. The admin actually gets help guessing what would help the user
6. Translations are not needed at all, since the users define the Tags. It would be useful to allow to define synonyms for filtering for the defined Tags. (e.g `#Tree` = `#Baum` or more practical `#desk` = `#furniture`)
7. The system is very dynamic and allows much more flexibility for the user, the admin and the developer (build a dynamic filter menu defined by the admin through tags etc...)

**So what now?**

We agreed on making it possible to disable Categories via an environment variable.

I understand @Tirokk when he says that a lot of work was put into that and it might be unwise to throw that away in light of some networks may be in need for static Categories.

Tho I want to spark the discussion if we want to use the chance that posting is currently not possible without defining categories (which are currently not seeded) to refactor the whole thing - Tags **could** (they cannot do that yet) fulfill all what categories do, as stated above.

**We can consider these options**

1. Disable via Config (✅ we agreed on that)
2. We could remove everything regarding Categories crippling the Software (features are lost)
3. Leave everything unchanged (🚫 I do not agree)
4. We could change it directly to a Tag system (e.g. Icons on post (which might need a synonym system already)). Removing the requirement to have Categories on a Post would not delay the release.

**Please review your position in light of this wall of text**

![](https://media1.tenor.com/images/74a87da6760e119fdfbb1ee9d2914871/tenor.gif?itemid=5437251)

![](https://media1.tenor.com/images/ac60e5be7508a7bb9aa854062ac5d8ca/tenor.gif?itemid=7183577)

**Comment by Mogge** [comment]
I agree with your argumentation. The only advantage, that categories actually have, is that they are presented in a more designed way (with icons, own layout). If we can achieve something similar with the tags we are in the right direction. I would not throw away the implementation of the categories from the code base.
The best solution for me is:
 1. Verify if we can switch of the categories easily (see #4101)
 2. if true then focus on the tags, else evaluate the effort again, discuss other solutions.

**Comment by Mogge** [comment]
In some unknown future, if categories could become interesting again, we can pick up what we have and see what we can do with it. Although I believe that if we have a good mechanism for the tags, the interest in having categories will fade away.

**Comment by Tirokk** [comment]
I agree with the most (if not all) of your arguments @ulfgebhardt .
I would go the way @Mogge points out and we see if ever the need of categories rises again. Okay?

What I really appreciate is that the create post page has less elements and loses weight.

*I do just a brainstorming about what are interesting differences:*

- downside of tags (hashtags) is that they can variate between languages and even in the same language and for the same things
  - so if you search you easier miss content you would be interested in
- categories can be the same over languages, because they are fixed they can have translations
  - PlanetRomeo uses tags therefore to store a lot of informations about the tastes of the users
  - the use is not so limited, but the question @ulfgebhardt rises is:
    - are categories a good solution for posts?
    - or the other way around: are there usages for ocelot.social and its posts where categories are good
- categories are easy to be overviewed and to choose, because there're not such a lot, there’re displayed like checkboxes, and they have not to be typed
- by categories the user can be reminded about which themes a network is about and make them think if the theme of their post is fitting here really well
