### ISSUE TITLE
🚀 [Feature] Admin Can Give Roles To Users

### ISSUE THREAD

**Issue by Tirokk** [Ocelot-Social-Community/Ocelot-Social#4124]
## :rocket: Feature

An admin should be able to give rolls to and change roles of users.

### User Problem

At the moment no user, not even an admin, can change rolls of users.
We do it per direct database manipulation.

### Implementation

I suggest to have a popup menu for the role of a user in the admins users list.

<img width="1702" alt="Bildschirmfoto 2021-01-11 um 09 04 02" src="https://user-images.githubusercontent.com/25344101/104158005-b6d91780-53ec-11eb-8606-c9f29da52a49.png">

### Design & Layout

See above ☝🏼

### Validation

None

### Additional context

None

**Comment by tippanamadhusudan** [comment]
Hi, I would like to take this issue. This is my first issue. Please assign this to me.

**Comment by Mogge** [comment]
Welcome @tippanamadhusudan.
Please let we know if you need any help.

**Comment by Mogge** [comment]
Please join our discord channel:
https://discordapp.com/invite/DFSjPaX
