### ISSUE TITLE
💥 [DevOps] Update CI Badges in Readme

### ISSUE THREAD

**Issue by ulfgebhardt** [Ocelot-Social-Community/Ocelot-Social#4171]
## :fire: DevOps ticket

Update CI Badges in `README.md`

![image](https://user-images.githubusercontent.com/1238238/106166618-a5359500-618c-11eb-876f-c2f990124317.png)

Those badges still point to the wrong Repo

**Comment by Abjcodes** [comment]
Hey @ulfgebhardt, Can I fix this issue?

**Comment by ulfgebhardt** [comment]
You are very welcome to. I invite you to the Orga als Volunteer. This will allow you to push branches (if accepted) so you do not need to fork.
![image](https://user-images.githubusercontent.com/1238238/106273823-90600c80-6233-11eb-9eae-2334e0e0c7b5.png)

<3

**Comment by Abjcodes** [comment]
@ulfgebhardt Thank you for the invitation. I will look into the issue.

**Comment by ulfgebhardt** [comment]
```
[![Coverage Status](https://coveralls.io/repos/github/Ocelot-Social-Community/Ocelot-Social/badge.svg)](https://coveralls.io/github/Ocelot-Social-Community/Ocelot-Social)
```

**Comment by Tirokk** [comment]
This was done somewhen
