### ISSUE TITLE
🐛 [Bug] Location Settings Are Broken

### ISSUE THREAD

**Issue by Mogge** [Ocelot-Social-Community/Ocelot-Social#4183]
## :bug: Bugreport
On the settings page, the user can no longer choose the location.

### Steps to reproduce the behavior
1. got to the settings
2. try to enter our city or region
3. nothing happens

### Expected behavior
As before, a user should be able to choose city or region.

### Additional context
`Uncaught (in promise) Error: Request failed with status code 401`

**Comment by ulfgebhardt** [comment]
This is actually a feature ;) It shows that the MAPBOX_TOKEN is exposed to the client when it should never be.
-> Solution is to move the call to the backend.
