### ISSUE TITLE
🔧 [Refactor] Invite Mails need an overhaul

### ISSUE THREAD

**Issue by ulfgebhardt** [Ocelot-Social-Community/Ocelot-Social#4235]
## :zap: Refactor ticket

Invite Mails need an overhaul

### Motive

- [ ] Adjustment to wir.social
- [x] brandable

### Additional Informations

related #4326

**Comment by Tirokk** [comment]
Ich denke dieser PR wurde durch #4326 gefixt?
Wenn du das auch so siehst @ulfgebhardt , dann schließ ihn gerne. 🤗

**Comment by Tirokk** [comment]
Is this still needed? @ulfgebhardt 

- Brandability is given now.
- The adjustment to wir.social, if necessary, should be issued on the rebranding repo of wir.social. Or?

**Comment by Tirokk** [comment]
I just close it …
