### ISSUE TITLE
🐛 [Bug] Long Hashtag Name In Hashtag List Is Not Visible

### ISSUE THREAD

**Issue by Tirokk** [Ocelot-Social-Community/Ocelot-Social#4253]
## :bug: Bugreport

Long hashtag name in hashtag list is not visible.

<img width="1813" alt="Bildschirmfoto 2021-02-19 um 22 59 38" src="https://user-images.githubusercontent.com/25344101/108993054-52bb9b80-769a-11eb-9816-eb74711c5afe.png">

### Steps to reproduce the behavior

1. login as admin
2. add a post with a long hashtag as '#HaliHaloDasIstEinFlohOhaOho'
3. in the users menu go to admin and here to hashtags
4. see the problem for long hashtags

### Expected behavior

See all hashtags names to a certain extend.

### Additional context

None

**Comment by Mogge** [comment]
It is more: when you click on the hashtag:
![image](https://user-images.githubusercontent.com/15882241/109011406-20696880-76b1-11eb-9d74-d3e59cde2826.png)

The related post is not found. We have trouble with Unlaut-encoding in our Tags.
