### ISSUE TITLE
🚀 [Feature] UI Restructuring

### ISSUE THREAD

**Issue by ulfgebhardt** [Ocelot-Social-Community/Ocelot-Social#4265]
## :rocket: Feature

Implement this

![donate+restruturing](https://user-images.githubusercontent.com/1238238/109210114-ae764980-77ac-11eb-9c0f-d38def0aa43e.png)

**Comment by ulfgebhardt** [comment]
Cafeul with mobile view regarding donations (must be collapsed on top) -> make donation box collapsable

**Comment by Tirokk** [comment]
This is fixed by #4357

**Comment by Tirokk** [comment]
This is fixed by #4357
