### ISSUE TITLE
🚀 [Feature] Make Show Password A Component And Implement in Registration Slider

### ISSUE THREAD

**Issue by Tirokk** [Ocelot-Social-Community/Ocelot-Social#4312]
## :rocket: Feature

Make show password a component and implement in registration slider.

- related PR #4270
- related issue #4092

### User Problem

```gherkin
Feature: Registration
  As a user
  I want to be able to see what I’m typing in the password input.
  In order to avoid wrong typings.
```

### Implementation

See `LoginForm.vue` as the example to put into a component.

- Implement here: `https://github.com/Ocelot-Social-Community/Ocelot-Social/blob/master/webapp/components/Registration/RegistrationSlideCreate.vue`
- May implement this in changing your own password as well?

### Design & Layout

See there as well.

### Validation

None

### Additional context

None

**Comment by Brandon-G-Tripp** [comment]
@Tirokk Hey I am looking to dive back into some issues. I apologizes for being off grid. I had some other projects I had to finish. Can I take a stab at this one?

**Comment by Tirokk** [comment]
Hey @Brandon-G-Tripp !
Cool to have you in action again! 🍀
Like you know it is absolutely okay if you have to care for other things. We are just happy to have you around.

I assigned you to this issue. 🤗

**Comment by Brandon-G-Tripp** [comment]
@Tirokk Is there a registration invite code to use for development?

**Comment by ulfgebhardt** [comment]
@Brandon-G-Tripp I am not sure I do understand what your asking, but if you ask for seed data, the seeded invite code for test purposes should be `AAAAAA`

**Comment by Tirokk** [comment]
@ulfgebhardt is right.

If you go to the Neo4j Browser at `http://localhost:7474/browser/` click on the top left database icon the `Database Information` menu on this side opens. Under `Node Labels` click on `InviteCode` and the node shows up.

Next step: If you send an e-mail to for verification you get the node in the same browser by:

```cypher
MATCH (email:UnverifiedEmailAddress {email: "github@pjannto.com"}) RETURN email;
```

Put your used e-Mail here …
More infos under PR: https://github.com/Ocelot-Social-Community/Ocelot-Social/pull/4270

**Comment by Brandon-G-Tripp** [comment]
Thats perfect thanks. @ulfgebhardt @Tirokk

**Comment by Brandon-G-Tripp** [comment]
@ulfgebhardt @Tirokk Is there also a default email confirmation code? I am trying to test the show password component on the registration slide.

**Comment by ulfgebhardt** [comment]
I do not have this information @Tirokk

**Comment by Tirokk** [comment]
I guess you mean the Cypher to get the e-mail verification nonce?

```cql
MATCH (email:EmailAddress {email: "wolle.huss@pjannto.com"}) RETURN email;
```

Replace with your e-mail.
I gave you the wrong one above ☝🏼 …

Or you mean something different?

The registration process can be tested in the storybook as well:

```bash
# in the webapp folder
$ yarn storybook
```

Got to `http://localhost:3002/?path=/story/registrationslider--invite-code-with-data`.

There you will find other opportunities in the left the menu.
This is quite nice for the start of the development …

**Comment by Tirokk** [comment]
@Brandon-G-Tripp PR #4370 fixed this issue. 🙏🏼
