### ISSUE TITLE
🐛 [Bug] Follow Relation Is Not Set At Invite

### ISSUE THREAD

**Issue by ulfgebhardt** [Ocelot-Social-Community/Ocelot-Social#4325]
## :bug: Bugreport

Follow relation is not set at invite.

- In the dev environment the relation is set, but the `INVITED` and the `FOLLOWS` relations have not `createdAt` property.
- Live there is no `INVITED` or `FOLLOWS` relation at all.

### Closer Problem

If the user in the registration process gets an e-mail verification e-mail and clicks the link then there is not invite code in it.
This causes the problem. In dev I get no real e-mail and therefore I don’t click a link and stay in the same registration slider configuration where the invite code is typed in.

### Todo

- [ ] set the relation to the invite node from the `emailAddress` node.
- [ ] care for `Wolle` comments

**Comment by Tirokk** [comment]
Closed in favour of #4336 .

**Comment by Tirokk** [comment]
Closed in favour of #4336 .
