### ISSUE TITLE
🐛 [Bug] Email Verification Sends Out Wrong Link

### ISSUE THREAD

**Issue by Mogge** [Ocelot-Social-Community/Ocelot-Social#4339]
## :bug: Bugreport

The email sent to verify the email address during signup contains a wrong link.
When starting here:

![email_entered](https://user-images.githubusercontent.com/15882241/113507923-90d79500-954d-11eb-99f1-ed209607dbfe.jpg)

You can see, that there is no method given in the URL.

This is en extract of the email the new user receives (please ignore the `\n +`, I have overseen this when cleaning up):

![email](https://user-images.githubusercontent.com/15882241/113508386-0ba1af80-9550-11eb-96d8-80c06762b0f1.jpg)

As you can see, there is a huge button shouting **CLICK ME** in your face, and further below, you see the actual nonce you are asked to enter during signup process.

There are very few users in this world, which would not click on the button and type in the nonce in the form instead.

But now, this is the link the button is pointing to:
```
http://localhost:3000/registration?method=invite-mail&email=test%40test.org&nonce=71967
```
And this  is what you see, when you click on it:

![nonce](https://user-images.githubusercontent.com/15882241/113508580-2163a480-9551-11eb-9aa0-eb16da70bf83.jpg)

You see, now we have a method in the URL, and it is the wrong one! We switched over to another signup method.

The dots do go back to the earlier steps of the registration process disappeared!

The backend has no chance to receive the invite code from this point on, because it does not exist in the frontend anymore. 

### Steps to reproduce the behavior
1. Got to `http://localhost:3000/registration`
2. Add a line `console.log(actionUrl)` to line 24 of `backend/middleware/email/templateBuilder.js` to see the link in the console.
3. Add a line `console.log(signupTemplate({ email, nonce })).html` to line 48 of `backend/src/middleware/email/emailMiddleware.js` to see the email in the console.
4. Step forward in the registration process until you get the email send.
5. Check the Link and the Email

### Expected behavior
The Link should point to the correct signup method or no link should be provided at all.

**Comment by Tirokk** [comment]
We discussed this all on Thursday @Mogge 
See my comment in your PR.
