### ISSUE TITLE
🔧 [Refactor] Multi-Usability Of Network Logos By Using Paths

### ISSUE THREAD

**Issue by Tirokk** [Ocelot-Social-Community/Ocelot-Social#4429]
## :zap: Refactor ticket

Establish a multi-usability of network logos by using paths in constant files.

### Motive

Some of the logos in folder `webapp/static/img/custom/` are just the same.

### Related issues

None

### Implementation

Therefore it would be nice to define paths in a file in folder `webapp/constants/` to be able to use the same logo file in different places respectively components.

### Additional context

None

**Comment by manthony9** [comment]
Hi @Tirokk can i take this issue up ?

**Comment by Tirokk** [comment]
Hey @manthony9 ,

I was on vacation till yesterday, because we had holidays. Sorry for my late replay.

Unfortunately I have fixed this at the end of last week with the PR #4433 and have forgotten to notice there that it will solve this issue as well. Therefore I have to close this issue.

Please look out for another one. 🙏🏼
Thanks for your patience!

Please get in contact to us on Discord if you like:
https://discord.com/invite/DFSjPaX

On Discord we have kind of every day a Daily Standup at UTC 09:30 am (CEST 11:30 am) in the Conference Room.
Looking forward to your help.

**Comment by Tirokk** [comment]
@manthony9 I gave you a Discord link which was expired. Please use https://discord.gg/AJSX9DCSUA .

Is fixed by PR #4433 .
