### ISSUE TITLE
🔧 [Refactor] Setup Gitbook

### ISSUE THREAD

**Issue by Tirokk** [Ocelot-Social-Community/Ocelot-Social#4460]
## :zap: Refactor ticket

Setup GitBook already running instance but not on a good link: (ask @Tirokk )
https://app.gitbook.com/@ocelot-social/s/ocelot-social-network/~/settings/customization

### TODO

- [ ] use it in main README.md
- [ ] use it in CONTRIBUTION.md

**Comment by mahula** [comment]
This has been done with Vuepress.
