### ISSUE TITLE
🐛 [Bug] Login And Register BaseCard Is Not Centered Anymore

### ISSUE THREAD

**Issue by Tirokk** [Ocelot-Social-Community/Ocelot-Social#4481]
### Steps to reproduce the behavior

1. go on the login or register page
2. see the problem

<img width="1232" alt="Bildschirmfoto 2021-06-11 um 09 53 12" src="https://user-images.githubusercontent.com/25344101/121652051-90063680-ca9b-11eb-9033-051f4eb26a36.png">
<img width="1232" alt="Bildschirmfoto 2021-06-11 um 09 53 22" src="https://user-images.githubusercontent.com/25344101/121652081-9694ae00-ca9b-11eb-93dc-7482f9427ab3.png">

### Expected behavior

It should look as on the password reset page: centered

<img width="1232" alt="Bildschirmfoto 2021-06-11 um 09 53 02" src="https://user-images.githubusercontent.com/25344101/121652162-a7ddba80-ca9b-11eb-998a-896736d5cf6f.png">

### Version & Environment

None

### Additional context

Probably just a CSS problem …

**Comment by somesh202** [comment]
@Tirokk   Can I work on this issue?

**Comment by ulfgebhardt** [comment]
Consider yourself assigned @somesh202 ❤️

**Comment by somesh202** [comment]
@ulfgebhardt I am unable to find the code related to this issue. Can you please guide me?

**Comment by somesh202** [comment]
Yes, I got the desired code, thanks a lot! But I am facing some issues while viewing the website on the development server. Due to which I cannot view the changes that occurred on the website.

**Comment by Tirokk** [comment]
It’s solved by #4660
