### ISSUE TITLE
🚀 [Feature] Single Person Org

### ISSUE THREAD

**Issue by Tirokk** [Ocelot-Social-Community/Ocelot-Social#4548]
## :rocket: Feature Request

relates #4544 

### Single Person Org

The `Single Person Org` is the first step of implementing orga, see EPIC #4544 and [1. Single Person Org](https://github.com/Ocelot-Social-Community/Ocelot-Social/issues/4544#1-single-person-orga) .

!!! IN WRITING !!!

##### Profile

- [ ] display org type

##### Post

- [ ] the displayed post author should include the org and the author

#### Network Admin

As network admin:

- [ ] switch org creation on and off
- [ ] switch org visibility on and off

#### Database

For the database model see [Database](https://github.com/Ocelot-Social-Community/Ocelot-Social/issues/4544#database).

#### Steps

Have a look on the collecting PR … #4701

**Comment by rbeer** [comment]
# asd
## fasfasf
### dfsdg
#### sdgsdjg

**Comment by ulfgebhardt** [comment]
Can we close this @Tirokk

**Comment by Tirokk** [comment]
Yes we can.

closed in favor of #5059
