### ISSUE TITLE
🐛 [Bug] Webapp – Unused Locale Identifiers

### ISSUE THREAD

**Issue by Tirokk** [Ocelot-Social-Community/Ocelot-Social#4598]
## :bug: Bug Report

There are several unused localisation identifiers which have to be removed:

- site.director
- site.taxident
- site.tribunal
- site.responsible

**Comment by Youspeakcubic** [comment]
@Tirokk Hello, Could i work on this? If so could you help me find where these identifiers are as well. i could not find them.

**Comment by Tirokk** [comment]
Sorry for the delay @Youspeakcubic . I’m on holidays and @ulfgebhardt is on a trip.

You find the localisation identifiers in the language JSONs: https://github.com/Ocelot-Social-Community/Ocelot-Social/tree/master/webapp/locales

Please check if they are really not used by a quick search of the last selector in the web apps code before remove them to be sure …
