### ISSUE TITLE
🔧 [Refactor] Linting Of Vue Makes Errors

### ISSUE THREAD

**Issue by Tirokk** [Ocelot-Social-Community/Ocelot-Social#4671]
## 🔧 Refactor

Linting of vue makes errors.

See PR #4670 .

<img width="1068" alt="Bildschirmfoto 2021-09-20 um 10 28 20" src="https://user-images.githubusercontent.com/25344101/133975022-5b9addcc-ee6d-4c2c-95bc-d4242c5aa550.png">

**Comment by Elweyn** [comment]
@Tirokk I don't think this is still an issue!?
