### ISSUE TITLE
🚀 [Feature] Put Footer Content In The Menu On Mobil Phones

### ISSUE THREAD

**Issue by Tirokk** [Ocelot-Social-Community/Ocelot-Social#4732]
## :rocket: Feature Request

Put footer some content in the menu on mobil phones to have more space on the screen.

- fixes #2292 as well, because it's the same

## Solution

- Put the most footer links into the header menu.
- Leave important legacy links in the footer. (ask @Tirokk and @UlfTramsen for further informations and for talk a bout a space saving solution)

<img width="507" alt="Bildschirmfoto 2021-10-18 um 17 12 01" src="https://user-images.githubusercontent.com/25344101/137759727-32fc89c3-6da8-46af-b6d3-3998de8c31f1.png">

**Comment by Tirokk** [comment]
Hey, cool! 😍

I assigned you to this issue @somesh202 🙏🏼

**Comment by somesh202** [comment]
Okay, Thanks !

**Comment by Tirokk** [comment]
Do ya need any help on this? @somesh202

**Comment by severicus** [comment]
Hello, if this issue is still open I'd like to handle it. If i may, i believe it would be better to just have the footer in a fixed position at the bottom and make it smaller so it doesn't overlap with other content unless this is an accessibility issue.
