### ISSUE TITLE
🐛 [Bug] Correct Notification Settings Link On Notification E-Mail And Enable Redirection

### ISSUE THREAD

**Issue by sushidave** [Ocelot-Social-Community/Ocelot-Social#4805]
## 🔧 Refactor
Refactor links in the notification email #4623 (implemented with version 1.0.6) and enable redirection:

- [x] Change link to the notifications settings from helfa.social/organization/settings/notifications to helfa.social/settings/notifications.
- [x] If the user is not logged in, redirect helfa.social/notifications to helfa.social/login?path=notifications.
- [x] If the user is not logged in, redirect helfa.social/settings/notifications to helfa.social/login?path=settings/notifications.

As discussed tonight with Andreas and @hermann-san.

@Tirokk

**Comment by Tirokk** [comment]
Hey and thanks to be so mindfulness. @sushidave @hermann-san

The first point about the wrong notification link is solved in my eyes by issue #4720 and PR #4742 .
But seems not to be updated on the network jet …

The redirections we have to checkout. Usually they are automatically correct. Maybe only if the link pint to an existing page which was not the case before we fixed the bug.
So this has to be tested …

**Comment by Tirokk** [comment]
I invited you to the team on this organisation @hermann-san .
Please accept 🍀

**Comment by hermann-san** [comment]
@Tirokk sure, it's just that I don't have access to a 1.0.6 network

**Comment by Tirokk** [comment]
That’s a pity!
Sorry for that. but I would drown if I wouldn’t set priorities somehow smart 😅
Time will come …

**Comment by Tirokk** [comment]
I checked all these thinks mentioned in the issue description and they work as expected.
As well is the new version 1.0.7 now on wir.social @hermann-san
