### ISSUE TITLE
🐛 [Bug] Fix username on e-mail notifications if multiple mentions

### ISSUE THREAD

**Issue by sushidave** [Ocelot-Social-Community/Ocelot-Social#4867]
## :bug: Bug Report

A wrong username is shown on e-mail notifications #4326 if multiple users have been mentioned in a comment. The e-mail notification shows the username of the last mentioned user instead of the one of the e-mail recipient.

Observed on wir.social. Please check.

**Comment by sushidave** [comment]
@Tirokk mentioned that it could be a caching issue.

**Comment by Tirokk** [comment]
This seems to be a temporary problem in the `wir.social` network.
As @sushidave and I tested it the next time it was gone.

**Comment by Tirokk** [comment]
Close, because was temporary 👆🏼

**Comment by Tirokk** [comment]
Close, because was temporary 👆🏼
