### ISSUE TITLE
🐛 [Bug] Embedded Youtube video too small

### ISSUE THREAD

**Issue by hermann-san** [Ocelot-Social-Community/Ocelot-Social#4881]
## :bug: Bug Report

When YouTube embedded video's are included in an article, they look somewhat not proportionate in general and it relation to the text.
The preview and the video itself should greater in hight or should be  square  , respectively adjusted to the browser window size (idealy). It's on Linux mint Firefox 96.0.1. It's the same with the Brave Browser and Android 7 - Firefox 90.1
In full screen mode the video is still fine
![Auswahl_008](https://user-images.githubusercontent.com/7679654/150092987-b06a7995-6f02-4637-a469-3fbc8f3c0e55.png)

**Comment by Tirokk** [comment]
Thanks @hermann-san . 😍
I have not found the time to create an issue the last days …
