### ISSUE TITLE
🔧 [Refactor] EnterNonce.vue Seems Unused And Should Be Removed

### ISSUE THREAD

**Issue by Tirokk** [Ocelot-Social-Community/Ocelot-Social#5035]
## 🔧 Refactor

`webapp/components/EnterNonce/EnterNonce.vue` seems to be unused and should be removed.

**Comment by msabirz** [comment]
Can I take up this ?

**Comment by Tirokk** [comment]
Hey @PrajwalBorkar ,

yes for sure you can take over. That’s great! 🤗
I assigned you to this issue.

I cared for your invitation to our community as volunteer via an e-mail invitation you can accept.

Our conversation runs over our discord server:
https://discord.gg/AJSX9DCSUA
There we have usually from Monday to Thursday a Daily Standup at UTC 09:30 am (CEST 11:30 am) in the Office Cube.

Please don’t compare from your fork to this repository, in case, because the publish action will fail, because of permission problems with the credentials.
Just push your branch directly to our repo and compare to the master.
If you accept the invitation then you’ll have the right todo so. 😉

**Comment by Tirokk** [comment]
Is not unused
