### ISSUE TITLE
🔧 [Refactor] Replace `gql` Tag Faking By Real `gql` Tag In Backend

### ISSUE THREAD

**Issue by Tirokk** [Ocelot-Social-Community/Ocelot-Social#5152]
## 🔧 Refactor

Replace `gql` tag faking in file `backend/src/helpers/jest.js` by real `gql` tag in backend, see the TODO in here.

**Comment by rabbanirizwan** [comment]
@Tirokk  I wanted to work on this

**Comment by Tirokk** [comment]
Hey @rabbanirizwan ,

sorry, I was in holidays.

Are ou still interested to work on this? 🤗
