### ISSUE TITLE
💥 [DevOps] Change Error Message With `Authorised` To `Authorized` All Over The Place To Have American English

### ISSUE THREAD

**Issue by Tirokk** [Ocelot-Social-Community/Ocelot-Social#5203]
## 💥 DevOps Ticket

Change error message with `Authorised` to `Authorized` all over the place to have american english.

**Comment by timagixe** [comment]
@Tirokk hello, can I help with it? Could you please assign this issue to me?

**Comment by Tirokk** [comment]
Hey @timagixe ,

yes for sure you can take over. That’s great! 🤗
I assigned you to this issue.

I cared for your invitation to our community as volunteer via an e-mail invitation you can accept.

Our conversation runs over our discord server:
https://discord.gg/AJSX9DCSUA
There we have usually from Monday to Thursday a Daily Standup at UTC 09:30 am (CEST 11:30 am) in the Office Cube.

Our conversation runs over our discord server:
https://discord.gg/Q7ZNG8sFrg
There we have usually from Monday to Thursday a Daily Standup at UTC 09:30 am (CEST 11:30 am) in the Office Cube.

Please don’t compare from your fork to this repository, in case, because the publish action will fail, because of permission problems with the credentials of the tests.
Just push your branch directly to our repo and compare to the master.
If you accept the invitation then you’ll have the right todo so. 😉
