### ISSUE TITLE
🔧 [Refactor] Disable Submit Button On Update Formular If Nothing Has Changed

### ISSUE THREAD

**Issue by ogerly** [Ocelot-Social-Community/Ocelot-Social#5472]
## 🔧 Refactor
when editing a group, the submit button will not work disable

**Comment by ogerly** [comment]
@Tirokk i have now tested the update grout form thing again and it now changes the submit button to disable if something doesn't match the formSchema. can you also look again? because then we could close the issues in my opinion

**Comment by Tirokk** [comment]
I guess you haven't understand the problem. @ogerly 

I f you edit the settings and you have not changed anything the submit button is already active.
But there is nothing to submit.
