### ISSUE TITLE
🔧 [Refactor] Move Add Users To Group As Members Above The Members List

### ISSUE THREAD

**Issue by Tirokk** [Ocelot-Social-Community/Ocelot-Social#5539]
## 🔧 Refactor ticket

On the group settings members page the add users to members base-card is part of the members list.

- a base-card on another base-card seems not good looking to me
- and a members list should be just the list of the members
- on the admin settings users page the search is as well above the users list

I would suggest to move the search and add user to group above the members list.

**Comment by Mogge** [comment]
@Tirokk Can I close this one? I think this was done by the add user to group PR

**Comment by Tirokk** [comment]
Done by PR @Mogge mentioned 👆🏼
