### ISSUE TITLE
🐛 [Bug] Locales Text on Delete User

### ISSUE THREAD

**Issue by Mogge** [Ocelot-Social-Community/Ocelot-Social#5594]
## 🐛 Bugreport

We get this broken locales when trying to delete an user:
![image](https://user-images.githubusercontent.com/15882241/198259421-44ff88d2-3e66-489a-8f73-ebd50cc42230.png)

**Comment by ogerly** [comment]
the error is currently not reconstuable for me. i have pulled the current master and it is displayed cleanly for me. it is also displayed cleanly on ocelot and yunite.

**Comment by Tirokk** [comment]
On production it looks correct like this:

<img width="1531" alt="Bildschirmfoto 2022-11-15 um 12 18 15" src="https://user-images.githubusercontent.com/25344101/201907080-704ef130-9aa4-4b8d-9374-22596afb7e39.png">
