### ISSUE TITLE
🔧 [Refactor] Post images start in cut tool

### ISSUE THREAD

**Issue by ulfgebhardt** [Ocelot-Social-Community/Ocelot-Social#5746]
## 🔧 Refactor ticket

Post images start in cut tool.

When uploading an image on a post you have the option to enable the cut tool to cut the image.

For usability reasons you should start with the tool activated without pressing an button. The default setting should be to just display the uncut image as it would been before, but with the option to cut it immediately.

**Comment by Tirokk** [comment]
@Mogge This seems already be done? Or?

**Comment by Mogge** [comment]
No, this is not done and I think that this is no good idea. We had this like this before and decided to remove it because of the bad user experience
