### ISSUE TITLE
🐛 [Bug] Yunite Color of Group tags

### ISSUE THREAD

**Issue by ulfgebhardt** [Ocelot-Social-Community/Ocelot-Social#5748]
## 🐛 Bugreport

Yunite Color of Group tags.

Group Tags have the wrong color on Yunite.

- [x] Fix the color
- [x] Do the same on the group profile
- [x] Figure out why this is not changed before - too many color definitions?

![image](https://user-images.githubusercontent.com/1238238/204253584-b215dcc4-6fcb-445e-83ce-670d98be3dfd.png)

<img width="1646" alt="215031214-0c70619e-daa9-452a-9f81-70093d324917" src="https://user-images.githubusercontent.com/25344101/215741929-39c97a2f-4adc-4b35-97a6-58a700df150b.png">

**Comment by ogerly** [comment]
done
