### ISSUE TITLE
🚀 [Feature] Filter – Show Filters As Buttons Above The News Feed

### ISSUE THREAD

**Issue by Tirokk** [Ocelot-Social-Community/Ocelot-Social#5793]
## 🚀 Feature

Show Filters As Buttons Above The News Feed.

- if I scroll down:
  - the header menu, the donation bar, and the filter buttons are vanishing: #5750
  - on mobile the open header menu should close in case?
- if I scroll then up a bit again:
  - header menu and filter buttons appearing again
  - the post feed disapears under the filter buttons
  - the donation bar is still not visible, because it is befor the first post and therefore still scrolled up under the header menu and filter buttons

### Issues

- relates #5750 
- relates #4245 

### Todo

- [ ] connect issue with Asana ticket

**Comment by ulfgebhardt** [comment]
closig in favor of #5818
