### ISSUE TITLE
💥 [DevOps] eliminate annotations for e2e tests

### ISSUE THREAD

**Issue by Mogge** [Ocelot-Social-Community/Ocelot-Social#5972]
There are annotations on the end to end tests in the CI:
 * `No files were found with the provided path: cypress/screenshots/. No artifacts will be uploaded.`
 * `The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/`

Can we improve the performance by deactivating videos and screenshots?

**Comment by mahula** [comment]
> Can we improve the performance by deactivating videos and screenshots?

Sure.
I will take care of that.
