### ISSUE TITLE
🐛 [Bug] Maintenance translation not working

### ISSUE THREAD

**Issue by ulfgebhardt** [Ocelot-Social-Community/Ocelot-Social#5981]
## 🐛 Bugreport

 Maintenance translation not working - only for French (yunite.me)

**Comment by Tirokk** [comment]
On ocelot it worked till the beginning of this year:

<img width="786" alt="Bildschirmfoto 2023-01-12 um 09 32 43" src="https://user-images.githubusercontent.com/25344101/220076168-cad5eb67-dfb7-4926-8c7c-2184c78e3a18.png">

On Yunite.me there was an error with this:

<img width="1646" alt="Bildschirmfoto 2022-12-13 um 11 50 51" src="https://user-images.githubusercontent.com/25344101/220076287-0cce8de9-6c64-4ceb-b370-77a94d12ec8d.png">
