### ISSUE TITLE
🚀 [Feature] Webapp – Change Design of Topics (Categories) of Post Teaser

### ISSUE THREAD

**Issue by Tirokk** [Ocelot-Social-Community/Ocelot-Social#5983]
## 🚀 Feature

Webapp – Change Design of Topics (Categories) of Post Teaser.

### Todo

- if a topic is marked as filtered the icon should be white

<img width="1646" alt="Bildschirmfoto 2023-02-16 um 21 03 23" src="https://user-images.githubusercontent.com/25344101/219476788-4c284d62-ad2e-4e8c-8a61-e4b3c2845030.png">

**Comment by khaledatia25** [comment]
Hello, I want to work on this issue

**Comment by Tirokk** [comment]
Hello @khaledatia25 ,

Sorry that I have overlooked your message!
But now.

Yes for sure you can work on this. That’s great! 🤗
I assigned you to this issue.

I cared for your invitation to our community as volunteer via an e-mail invitation you can accept.

Our conversation runs over our discord server:
https://discord.gg/AJSX9DCSUA
Please use our chat channel to ping me ( @Wolle (Hamburg)#8013 ).

Please don’t compare from your fork to this repository, in case, because the publish action will fail, because of permission problems with the credentials.
Just push your branch directly to our repo and compare to the master.
If you accept the invitation then you’ll have the right todo so. 😉

**Comment by Tirokk** [comment]
Hey @khaledatia25 

do you working on this?
Because we like to have it in the next release in two weeks or so …
