### ISSUE TITLE
🚀 [Feature] Webapp - User Profile About Should be Centered

### ISSUE THREAD

**Issue by Tirokk** [Ocelot-Social-Community/Ocelot-Social#5995]
## 🚀 Feature

Webapp - User Profile About Should be Centered.

<img width="1646" alt="Bildschirmfoto 2023-02-06 um 20 20 18" src="https://user-images.githubusercontent.com/25344101/220079789-7f6d8702-3ec9-4ac6-82cf-07a8147386ee.png">

**Comment by appinteractive** [comment]
Would look bad and be worse in readability with multi line text I guess, just as an input ;)

**Comment by Tirokk** [comment]
Moin, moin @appinteractive !

At the moment it looks like this on the groups profile. (The green chips have to get the dark green primary color of Yunite for sure.)
To be rethinkable.

My intention is to get the profiles to have the same design.

<img width="1646" alt="Bildschirmfoto 2023-02-21 um 09 22 49" src="https://user-images.githubusercontent.com/25344101/220288595-3b0c8c10-ac94-47e9-8255-cdad07d5c466.png">

**Comment by appinteractive** [comment]
I would never center text without very good reason, I do not see one here. Just my opinion.

**Comment by Tirokk** [comment]
We appresiate your opinion @appinteractive and I understand what you mean. Escpecially if the text is multilined. 🤗
I take that in mind for future refactorings. 👍🏼
