### ISSUE TITLE
🔧 [Refactor] Kubernetes charts always use latest images(branded), define it properly

### ISSUE THREAD

**Issue by ulfgebhardt** [Ocelot-Social-Community/Ocelot-Social#6004]
## 🔧 Refactor ticket

Kubernetes charts always use latest images(branded), define it properly

We currently use `appVersion` in the Chart to define the tag used of all images, but its never set and therefore always use `latest`.

- [ ] Investigate
- [ ] Make it properly versionized to make things reproducable
- [ ] Deployment scripts

**Comment by Tirokk** [comment]
- seems related to #6360 
  - may this here is outdated and need to be closed?
