### ISSUE TITLE
🚀 [Feature] Webapp – Join / Leave Button on Group Page is Misleading

### ISSUE THREAD

**Issue by Tirokk** [Ocelot-Social-Community/Ocelot-Social#6014]
## 🚀 Feature

Webapp – Join / Leave Button on Group Page is Misleading.

### Problem

If I join a closed group and become a pending member the button states, that I am a meber already.
Only underneath in my role I can see that I am pending. That's not clear enough.

### Todo

- if I'm a pending member change the join/leave button title to `membership penting`:
  - EN: `I'm a member` → `Pending member` (or something a bit shorter)
  - DE `Bin Mitglied` → `Ausstehendes Mitglied` (or something a bit shorter)
- additional change the role tranlations of the role `usual` to:
  - EN: `Simple Member` → `Member`
  - DE `Einfaches Mitglied` → `Mitglied`

**Comment by mahula** [comment]
@Tirokk ,
for a pending member I used the `question-circle` icon on the `JoinLeaveButton`.
Can we use it there or another one like the `user-plus` icon (see PR #6124)?
And should we use a different color forthe button,when user is pending?
