### ISSUE TITLE
🚀 [Feature] Webapp – Optimize Filter Buttons

### ISSUE THREAD

**Issue by Tirokk** [Ocelot-Social-Community/Ocelot-Social#6015]
## 🚀 Feature

Webapp – Optimize Filter Buttons.

### Todo

- move the `x` button as circled button into the filter button
  - do we need to extend the button component with the `x` button internally or have a wrap around component?
<img width="1646" alt="Bildschirmfoto 2023-02-22 um 17 33 35" src="https://user-images.githubusercontent.com/25344101/220694262-954b7939-6709-4b21-bf5d-355eaa8bc3bc.png">

- have a straight fade out edge under which the posts disappear
<img width="1646" alt="Bildschirmfoto 2023-02-22 um 17 33 48" src="https://user-images.githubusercontent.com/25344101/220694449-62419aa6-cbec-48de-b2e1-7f53ac68df2c.png">

**Comment by Elweyn** [comment]
Function of the filter button has to check if donation-bar is active

**Comment by Tirokk** [comment]
Hier sonst gerne zwei Issues draus machen. @Elweyn
