### ISSUE TITLE
🚀 [Feature] Webapp – Optimize Notification Page For Mobility

### ISSUE THREAD

**Issue by Tirokk** [Ocelot-Social-Community/Ocelot-Social#6016]
## 🚀 Feature

Webapp – Optimize Notification Page For Mobility.

### Problem

On mobile the notifications table is to wide. One can scroll it sideways, but this is not cool:

![image-4](https://user-images.githubusercontent.com/25344101/220686787-8d3a53a5-d150-4cf2-9d64-59ce4ff6f142.png)

On desktop the table looks this way:

![image-3](https://user-images.githubusercontent.com/25344101/220686977-7d4e3a67-6762-4ca5-a16c-9cd811b9f164.png)

**Comment by Elweyn** [comment]
Think about refactor from tables to grid with base-cards

**Comment by Tirokk** [comment]
Solved by  #6116
