### ISSUE TITLE
🚀 [Feature] Webapp – Improve Visual Delimitation of Posts in the Newsfeed

### ISSUE THREAD

**Issue by Tirokk** [Ocelot-Social-Community/Ocelot-Social#6017]
## 🚀 Feature

Webapp – Improve Visual Delimitation of Posts in the Newsfeed.

### Problem

The Newsfeed looks a bit to much chaotic:

- difference posts with and without images is cluttered and unattractive

<img width="1646" alt="Bildschirmfoto 2023-02-22 um 17 40 44" src="https://user-images.githubusercontent.com/25344101/220696940-807226b4-4d73-4b93-9684-2bea2d2b1c47.png">

### Ideas

- increase spacing at the bottom of the post or have more intense shadows
- who has good ideas?
  - see the hints and suggestions of @appinteractive below in the comments! 🙏🏼

**Comment by Tirokk** [comment]
Hey @appinteractive .
Do you have an idea to better the problem?

**Comment by appinteractive** [comment]
Take a look at my last design before I left HC: https://hc-concepts.vercel.app/

**Comment by Tirokk** [comment]
Thanks for your work and hint @appinteractive 👍🏼🙏🏼

**Comment by larsebert** [comment]
Most simple solution sufficient for now!
e.g.: Just increase spacing at the bottom of the post

**Comment by Tirokk** [comment]
Is fixed
