### ISSUE TITLE
🚀 [Feature] Webapp – Groups – If You Post in a Group On Post Create Page have the Topics of the Group Chosen by Default

### ISSUE THREAD

**Issue by Tirokk** [Ocelot-Social-Community/Ocelot-Social#6067]
## 🚀 Feature

Webapp – Groups – If You Post in a Group On Post Create Page have the Topics of the Group Chosen by Default.

A user can change the topics of the post for sure.

**Comment by Elweyn** [comment]
@Mogge this has been done if I remember well!?

**Comment by Elweyn** [comment]
Works on master branch
