### ISSUE TITLE
🐛 [Bug] Webapp – Avatars are not Visible in Group Member Lists

### ISSUE THREAD

**Issue by Tirokk** [Ocelot-Social-Community/Ocelot-Social#6133]
## 🐛 Bugreport

Webapp – Avatars are not Visible in Group Member Lists.

<img width="1129" alt="Bildschirmfoto 2023-03-14 um 12 54 00" src="https://user-images.githubusercontent.com/25344101/224998012-0361f20b-ce1f-4ca6-8eb8-b8ee35dd9e41.png">

### Todo

- make the avatar pictures visible in the two different group memeber lists

**Comment by sushidave** [comment]
Profile images on the member list in the admin area still missing.

**Comment by Elweyn** [comment]
@sushidave would like to close this one since the title of ticket describe the group describe for the admin overview we make a new ticket for the second issue.
