### ISSUE TITLE
💬 [Question] Chat – Developer Discussion and Recherche how to Implement a Chat

### ISSUE THREAD

**Issue by Tirokk** [Ocelot-Social-Community/Ocelot-Social#6139]
## 💬 Question

Chat – Developer Discussion and Recherche how to Implement a Chat.

### Possibilities

- refactor the comment list to use it as a chat message list
  - backend/database has to be developed
- use a chat frontend package to implement it
  - backend/database has to be developed
- integrate a separate chat tool into our code and deployment
  - probably includes a new and different database
  - see #4545

**Comment by ulfgebhardt** [comment]
We figured out that within the given context (time and money) only an internal solution is suitable. This means we handle storage & apis ourselfs. It is unclear if there might be libraries that could assist us to archieve this goal.
