### ISSUE TITLE
🔧 [Refactor] Webapp – Filter Menu – Reduce the Space Usage of the Menu Items by Reducing Gaps

### ISSUE THREAD

**Issue by Tirokk** [Ocelot-Social-Community/Ocelot-Social#6140]
## 🔧 Refactor ticket

Webapp – Filter Menu – Reduce the Space Usage of the Menu Items by Reducing Gaps.

<img width="1218" alt="Bildschirmfoto 2023-03-15 um 13 07 53" src="https://user-images.githubusercontent.com/25344101/225305704-6e849766-3b57-442a-ba72-fbfa810803f7.png">

**Comment by larsebert** [comment]
Achtung: Wir gehen komplett weg von den Kreisen! Sie nehmen zu viel Platz weg.

**Comment by Tirokk** [comment]
This is done
