### ISSUE TITLE
🚀 [Feature] Backend – Events, Newsfeed – Filter by Article and Events

### ISSUE THREAD

**Issue by Tirokk** [Ocelot-Social-Community/Ocelot-Social#6161]
## 🚀 Feature

In the newsfeed a user need more filter possibilities for:

- articles
- events:
  - on default don't show ended events
  - optional:
    - can show ended events as well
    - seperate: sort by event date, see #6190

**Comment by Elweyn** [comment]
Is merged in event-master!
