### ISSUE TITLE
🚀 [Feature] Webapp, Backend – Newsfeed, Filter Menu, Events – Sort by Event Date

### ISSUE THREAD

**Issue by Tirokk** [Ocelot-Social-Community/Ocelot-Social#6190]
## 🚀 Feature

In the newsfeed a user need more filter possibilities for:

- events:
  - optional:
    - sort by event date

Should the feed be automaticly sorted by event date if just events are shown?
( @Tirokk has to clearify)

- if event is selected
  - event start date with start after now
  - possibility of search of already finished events
  - sorting ORDER BY "Start date" ASC

![FilterAllgemein](https://github.com/Ocelot-Social-Community/Ocelot-Social/assets/33051975/6970d8a8-0597-41dd-bf8d-8770323d1b1e)

**Comment by Elweyn** [comment]
Maybe duplicate with https://github.com/Ocelot-Social-Community/Ocelot-Social/issues/6161
If yes then please close on of the two

Have this from our meeting:
- Wenn Event ausgewählt ist
  - Start date ab jetzt (Default)
  - Search of already finished Events
  - Sorting ORDER BY „Start date“ ASC

**Comment by Elweyn** [comment]
Maybe duplicate with #6046 

The 3 tickets should be merged

**Comment by Tirokk** [comment]
Solved by #6046

**Comment by Tirokk** [comment]
Solved by #6046
