### ISSUE TITLE
🐛 [Bug] Webapp - Group admin page does not show images of member list

### ISSUE THREAD

**Issue by Elweyn** [Ocelot-Social-Community/Ocelot-Social#6317]
## 🐛 Bugreport

![grafik](https://user-images.githubusercontent.com/25344101/224997954-981c93a3-4474-487c-8033-bd907dd7e4a0.png)

A similar solution have been done on group overview see #6258

**Comment by ulfgebhardt** [comment]
This should be fixed by https://github.com/Ocelot-Social-Community/Ocelot-Social/pull/6289
Will close after i confirm this on latest master

**Comment by ulfgebhardt** [comment]
![image](https://github.com/Ocelot-Social-Community/Ocelot-Social/assets/1238238/f04d23e5-a6b5-470c-8d8d-21be95d017ce)
