### ISSUE TITLE
🐛 [Bug] Webapp: Create Post page wrong button design

### ISSUE THREAD

**Issue by Elweyn** [Ocelot-Social-Community/Ocelot-Social#6443]
## 🐛 Bugreport

![image-4](https://github.com/Ocelot-Social-Community/Ocelot-Social/assets/25344101/5ae968e6-5b43-47c1-8811-92887a38b775)

## 🤖 TODO

- [ ] use the site menu component for the post types:
  - [ ] menu items:
    - EN:
      - `Article`
      - `Event`
    - DE:
      - `Beitrag`
      - `Veranstaltung`
  - [ ] have a headline that descrips what is happening
    - EN:
      - `Create an Article`
      - `Create an Event`
    - DE:
      - `Erstelle einen Beitrag`
      - `Erstelle eine Veranstaltung`

**Comment by Tirokk** [comment]
I tried it, but it's a m… . @Elweyn 
It's not so easy like I thought.
I would need more time for it.
