### ISSUE TITLE
🚀 [Feature][Webapp] Chat page should have a header ``Chat``

### ISSUE THREAD

**Issue by Elweyn** [Ocelot-Social-Community/Ocelot-Social#6545]
## 🚀 Feature

On the /chat page we only see the Chat Component.
At the start of the page their should be a Header with the text ``Chat``

## 🤖 ToDo
- [x] Chat page should have a header (Like Post, Events, ..) ``Chat``

**Comment by Tirokk** [comment]
The PR branch is ready but not pushed yet, because of GitHub Actions time management.
