### ISSUE TITLE
🐛 [Bug][Continus Integration] End-to-End test cleanup by failed job

### ISSUE THREAD

**Issue by Elweyn** [Ocelot-Social-Community/Ocelot-Social#6600]
## 🐛 Bugreport

If one part of the end-to-end fails the cleanup job is called and when restarting the failed end-to-end part it can't run anymore.
Please call the cleanup job only if every end-to-end test was successful so we can reuse the prepared environment.

## 🤖 ToDo
- [x] Call the cleanup job only if every end-to-end test was successful

**Comment by mahula** [comment]
This fix has been part of #6604.
