### ISSUE TITLE
🚀 [Feature] Chat: Display chat item in avatar navigation menu

### ISSUE THREAD

**Issue by sushidave** [Ocelot-Social-Community/Ocelot-Social#6678]
## 🚀 Feature

The link to the chat page is missing in the avatar navigation menu.

![2023-09-13-avatar-menu](https://github.com/Ocelot-Social-Community/Ocelot-Social/assets/17728384/60bd47cc-0289-47f2-9fb4-986c03761f0b)

Tasks:
- [ ] Add link to chat page (as of release 3.0.0).

As discussed with @Tirokk .

**Comment by ATREAY** [comment]
Hey @sushidave, if this issue is still open, could you please specify where it's occurring? 
I've tested all the chat buttons in the navigation and the avatar, and they seem to be working fine.

**Comment by sushidave** [comment]
@ATREAY 
Namasté Atreay, welcome to the Ocelot.Social project! 
Yes, this issue is still open. I just added a screenshot of the avatar menu so you see where the link is missing. I guess you can add it below the "All notifications" link. That one which will be renamed to "Notifcations" (see #6679) so you might want to team up with Scott. Thanks!
@Tirokk Please assign this issue to Atreay and provide him with further details.

**Comment by ATREAY** [comment]
Hey @sushidave, thanks for clearing that up. I'll work on it and let you know once it's sorted out.

**Comment by sushidave** [comment]
@ATREAY My pleasure and thank you very much!
I just found out that I am able to assign issues, so I am assigning this one to you. More details to follow from Tirokk.

**Comment by sushidave** [comment]
@ATREAY 
Thanks for your patience. We are waiting for @Tirokk to invite you to the community of voluteers here on GitHub. 
What I can share with you already is that the developer's conversation runs over this Discord server: https://discord.gg/AJSX9DCSUA. There you can use the chat channel to ping him ( @wolle (Hamburg)#8013 ).

**Comment by Tirokk** [comment]
I invited you @ATREAY

**Comment by ATREAY** [comment]
Thanks, @Tirokk and @sushidave! I'll definitely join the Discord and GitHub community channels.

**Comment by sushidave** [comment]
@ATREAY My pleasure. We are looking forward to see you on Discord where the developers will be glad to help you.

**Comment by Tirokk** [comment]
Are you still interested to work on this issue?
Do you had any problems? @ATREAY
