### ISSUE TITLE
🚀 [Feature] Change link text of notifications item in the avatar navigation menu

### ISSUE THREAD

**Issue by sushidave** [Ocelot-Social-Community/Ocelot-Social#6679]
## 🚀 Feature

Rename the link text of the "All notifications" item to "Notifications".

As discussed with @Tirokk .

**Comment by smhenderson89** [comment]
I can take this one. You are referring to the text here? @sushidave 
![EA5BF64C-44FF-41C4-A6ED-BC91B515B654_4_5005_c](https://github.com/Ocelot-Social-Community/Ocelot-Social/assets/53064568/8df05384-17da-4852-a69c-635b600ae4ab)

**Comment by sushidave** [comment]
@smhenderson89 Scott, you can take this one, too. Yes, it's the text I am referring to. Next time I should add some screenshots :o) @Tirokk is going to assign it to you. Thanks a lot!

**Comment by smhenderson89** [comment]
@sushidave hehe yes pictures do tend to help. Especially for new people, I found this issue through https://up-for-grabs.net/ so I didn’t know this project existed yesterday 😆

sounds good, I’ll start working on it.

**Comment by sushidave** [comment]
@smhenderson89 That's good to know, thanks for sharing this info on Up for Grabs. 

I just realized that I am able to assign issues, so I'm assigning this one to you.

Please see issue #6678 which is about another modification of the avatar menu. Atreay was asking to tackle it so it might be nice if you and Atreay coordinate your efforts.

**Comment by Tirokk** [comment]
I invited you @smhenderson89
