### ISSUE TITLE
🚀 [Feature] Rename top navigation menu items

### ISSUE THREAD

**Issue by sushidave** [Ocelot-Social-Community/Ocelot-Social#6680]
## 🚀 Feature

Simplify the naming (hints) of the top menu items, e.g. 

From:
- My chats
- My notifications
- Show groups
- Show map

To:
- Chats
- Notifications
- Groups
- Map

As discussed with @Tirokk .

**Comment by smhenderson89** [comment]
@sushidave is this available to be worked on? If so I'd like to tackle this issue.

**Comment by smhenderson89** [comment]
![8DB80BF2-9171-4D4E-8507-BD3CFE245B18_4_5005_c](https://github.com/Ocelot-Social-Community/Ocelot-Social/assets/53064568/de6a9a4d-b933-43c5-8342-74dc02928350)

Just double checking, you are referring to the hint text when hovering over the items for the navbar icons? (like in the picture?) @sushidave

**Comment by sushidave** [comment]
@smhenderson89 Hi Scott, welcome to this project! The issue is available for you. And yes, it's the hint text as shown in your picture. Thank you for contributing!
@Tirokk Can you please provide Scott with further details so he can tackle this issue?

**Comment by sushidave** [comment]
@smhenderson89 
Thanks for your patience. We are waiting for @Tirokk to invite you to the community of volunteers here on GitHub. 

What I can share with you already is that the developer's conversation runs over this Discord server: https://discord.gg/AJSX9DCSUA. There you can use the chat channel to ping him ( @wolle (Hamburg)#8013 ).

Once you're invited and accepted it please don’t compare from your fork to this repository because the publish action would fail due to permission problems with the credentials. Instead, you can just push your branch directly to our repo and compare it to the master.

**Comment by Tirokk** [comment]
I invited you @smhenderson89

**Comment by Rishi1314** [comment]
Hey, I'd like to work on this issue. Is it still available?

**Comment by smhenderson89** [comment]
@Rishi1314 Go for it. I tried getting a dev environment working, but had trouble getting the docker version of the website tow work. Maybe you have better luck than me :)

**Comment by sushidave** [comment]
@Rishi1314 
Namaste Rishi and thank you for taking over.

@smhenderson89 
Scott, thanks a lot for your comment. I'm sorry that you had trouble with the [docker version](https://github.com/Ocelot-Social-Community/Ocelot-Social/#docker-installation). Can you tell us where the problem happened? We are always interested in improving the documentation and adding tips for trouble-shooting.

**Comment by Tirokk** [comment]
> @Rishi1314 Go for it. I tried getting a dev environment working, but had trouble getting the docker version of the website tow work. Maybe you have better luck than me :)

Did you work on Windows @smhenderson89 ?

**Comment by smhenderson89** [comment]
> > @Rishi1314 Go for it. I tried getting a dev environment working, but had trouble getting the docker version of the website tow work. Maybe you have better luck than me :)
> 
> Did you work on Windows @smhenderson89 ?

No I was working on a Mac.

**Comment by Tirokk** [comment]
> > > @Rishi1314 Go for it. I tried getting a dev environment working, but had trouble getting the docker version of the website tow work. Maybe you have better luck than me :)
> > 
> > 
> > Did you work on Windows @smhenderson89 ?
> 
> No I was working on a Mac.

On a M1 Apple Silicon architecture?
In case I worked on M1 and on M2 Apple Silicon now and got it running after struggling at the beginning.
