### ISSUE TITLE
🐛 [Bug][Webapp] Map – Group Link on Popup is Wrong

### ISSUE THREAD

**Issue by Tirokk** [Ocelot-Social-Community/Ocelot-Social#6687]
## 🐛 Bugreport

Map – Group Link on Popup is Wrong.

<img width="1207" alt="Bildschirmfoto 2023-08-15 um 11 52 06" src="https://github.com/Ocelot-Social-Community/Ocelot-Social/assets/25344101/54b1c92f-c7ca-4536-a33d-66ae42bbf293">

<img width="1531" alt="Bildschirmfoto 2023-08-15 um 11 50 34" src="https://github.com/Ocelot-Social-Community/Ocelot-Social/assets/25344101/516f5e7e-90db-405f-a8ae-2e416e3ccbda">

**Comment by Tirokk** [comment]
May you like to take this issue @javierlpzdr ?

**Comment by Tirokk** [comment]
This one is a real and easy problem. @javierlpzdr

**Comment by javierlpzdr** [comment]
@Tirokk ok!
I pick this first

**Comment by Tirokk** [comment]
Great!

**Comment by javierlpzdr** [comment]
Hello @Tirokk ! 
I created this PR https://github.com/Ocelot-Social-Community/Ocelot-Social/pull/6698
