### ISSUE TITLE
🐛 [Bug][Webapp] Event – Missing Date on macOS Safari

### ISSUE THREAD

**Issue by Tirokk** [Ocelot-Social-Community/Ocelot-Social#6688]
## 🐛 Bugreport

Event – Missing Date on macOS Safari.

Correct shown on macOS Firefox:

<img width="835" alt="Bildschirmfoto 2023-08-15 um 12 34 42" src="https://github.com/Ocelot-Social-Community/Ocelot-Social/assets/25344101/4befa2c5-c510-4f1c-9a78-3479e742e173">

Missing on macOS Safari:

<img width="856" alt="Bildschirmfoto 2023-08-15 um 12 35 31" src="https://github.com/Ocelot-Social-Community/Ocelot-Social/assets/25344101/fe14ad0b-7304-41ac-b987-6481baa0d24f">

It is missing in the post teaser as well:

<img width="1318" alt="Bildschirmfoto 2023-08-17 um 16 04 32" src="https://github.com/Ocelot-Social-Community/Ocelot-Social/assets/25344101/967a1017-92e7-4592-9fbf-f176c133ba09">

On macOS Safari I get the console error:

<img width="1286" alt="Bildschirmfoto 2023-08-18 um 12 54 15" src="https://github.com/Ocelot-Social-Community/Ocelot-Social/assets/25344101/6e3afaa8-7e26-42a4-bd3f-91c67e0149a7">

**Comment by Tirokk** [comment]
Or this one @javierlpzdr ?
In case you have a Mac.

You already setup the project?

**Comment by javierlpzdr** [comment]
Ok! I can take this :) thanks for the suggestion. I will take a look later
today. Then I’m going to remove myself from the other issue.

I started installing the setup but when I tried to start docker I took too
long. I will try it again today.

I’ll keep you posted

**Comment by Tirokk** [comment]
Cool dear! @javierlpzdr

**Comment by javierlpzdr** [comment]
Hi @Tirokk,

I could finished installing everything (I had problems with the ram configuration for Colima). I took a look at the page and in my case, I can see the date in Safari. Could you give more details about the version? Maybe it happens in a older version (I can explore more tomorrow).

Thanks in advance

<img width="1318" alt="Screenshot 2023-08-17 at 00 40 51" src="https://github.com/Ocelot-Social-Community/Ocelot-Social/assets/10226319/5bcbcaa9-aad0-4071-ac65-a07eb844563e">

**Comment by Tirokk** [comment]
Interesting!

This is my Safari:

<img width="1318" alt="Bildschirmfoto 2023-08-17 um 16 04 32" src="https://github.com/Ocelot-Social-Community/Ocelot-Social/assets/25344101/967a1017-92e7-4592-9fbf-f176c133ba09">

**Comment by Tirokk** [comment]
May be this is a false bug which is related to the sender.fm network for an unknown reason.

<img width="1180" alt="Bildschirmfoto 2023-08-17 um 17 09 31" src="https://github.com/Ocelot-Social-Community/Ocelot-Social/assets/25344101/2ede54f2-0f88-4496-9cee-13d2036297fc">

Looks like you should go for another issue.
Sorry for that dear! 🙏🏼 @javierlpzdr

**Comment by Tirokk** [comment]
But I have the problem as well on my iPhone 13pro in Safari:

![IMG_8410](https://github.com/Ocelot-Social-Community/Ocelot-Social/assets/25344101/98a398a5-bbbf-471c-9697-62b1e4dc3577)

And even in Firefox:

![IMG_8412](https://github.com/Ocelot-Social-Community/Ocelot-Social/assets/25344101/cbd9463e-2d4f-4b2c-a21a-41f8d3db80af)

**Comment by javierlpzdr** [comment]
I see this was commented in another issue,
Btw, I'm going to take a look at it regarding the issues in the different devices,
It's quite weird 🤔 maybe it's something related with the content

**Comment by javierlpzdr** [comment]
Aha, I've got it!

It's about the Safari version, 'date-fns' and the date format, I could it replicate it in Safari 15 and the date isn't shown because there's an error with the format range:

![20230831_22_20_54_safari_15](https://github.com/Ocelot-Social-Community/Ocelot-Social/assets/10226319/1e876106-9a01-4428-aeb4-ddf25b19c94f)

I've been digging into the library issues and I found this:
https://github.com/date-fns/date-fns/issues/2130#issuecomment-1329675847

I'm pretty sure the issue is the same, since the date comes with the format similar to "2023-09-18 18:30:00" (if not... it could be due to the dots int the DE format -> dd.MM.yyyy but I had the same issue for EN).

For Safari 16 it worked fine, but we could changed how it's sent from BE to add some "retro-compatibility".

Feel free to let me know what's your opinion :)

**Comment by Tirokk** [comment]
What do you say @maeckes-infinitylabs ?

**Comment by Tirokk** [comment]
@Mogge fixed this as well by #6784 as far I understand?

Then you can close it.

**Comment by Tirokk** [comment]
fixed by #6784
