### ISSUE TITLE
💥 [DevOps] Setup GitBook with GitHub Pages for our Repo

### ISSUE THREAD

**Issue by Tirokk** [Ocelot-Social-Community/Ocelot-Social#6689]
## 💥 DevOps ticket

Setup GitBook with GitHub Pages for our Repo.

**Comment by mahula** [comment]
This won't be done, since the documentation automation has been implementend with Vuepress in #6836.

**Comment by mahula** [comment]
This won't be done, since a vuepress-based documentation automation has been implemented (see #6836)
