### ISSUE TITLE
🚀 [Feature] Chat: Only show counter if unread messages exist

### ISSUE THREAD

**Issue by sushidave** [Ocelot-Social-Community/Ocelot-Social#6750]
## 🚀 Feature

Currently, a counter 0 is shown if there are no unread chat messages. This is not needed and inconsistent with the logic of the notifications counter.

![2023-09-23-unread-chat-counter-zero](https://github.com/Ocelot-Social-Community/Ocelot-Social/assets/17728384/299d9c15-06e3-4050-9ec3-40c248bf5b08)

**Solution**
Only show counter if there are any unread messages.

**Comment by sushidave** [comment]
@tarunsamanta2k20 
Namaste Tarun and welcome to this project!
You are welcome to work on this issue. I'm assigning it to you and @Tirokk will invite you to our volunteers community soon.
The developer's conversation runs over this Discord server: https://discord.gg/AJSX9DCSUA. There you can use the chat channel to ping @Tirokk ( @wolle (Hamburg)#8013 ). 
Please don’t compare from your fork to this repository because the publish action will fail due to permission problems with the credentials. Instead, you can just push your branch directly to our repo and compare it to the master. You'll be allowed to do so after accepting the before mentioned invitation.

**Comment by Tirokk** [comment]
I invited you to the volunteers team @tarunsamanta2k20

**Comment by sushidave** [comment]
@tarunsamanta2k20 
Hey Tarun, thanks for your work. Your PR became part of trelease 3.1.1 which is going to be deployed to the live networks that use the ocelot.social software. Thank you very much for contributing!
