### ISSUE TITLE
🐛 [Bug] Webapp – Content Menu Moved to an Unwanted Position

### ISSUE THREAD

**Issue by Tirokk** [Ocelot-Social-Community/Ocelot-Social#6759]
## 🐛 Bugreport

Content Menu Moved to an Unwanted Possition.

<img width="352" alt="Bildschirmfoto 2023-09-07 um 12 37 03" src="https://github.com/Ocelot-Social-Community/Ocelot-Social/assets/25344101/4bae2719-6b41-4df4-83f3-eaf5a1c7f0fd">

The position like on the user profile is the wanted one:

<img width="337" alt="Bildschirmfoto 2023-09-26 um 18 59 21" src="https://github.com/Ocelot-Social-Community/Ocelot-Social/assets/25344101/a45be5c2-d206-4c3f-b99c-b143eaaaf526">

**Comment by Gauravtripathii** [comment]
Hi.  I'm interested in working on this issue.
