### ISSUE TITLE
🐛 [Bug] Authorization error

### ISSUE THREAD

**Issue by Butonix** [Ocelot-Social-Community/Ocelot-Social#6806]
`GraphQL error: Aggregation column contains implicit grouping expressions. For example, in 'RETURN n.a, n.a + n.b + count(*)' the aggregation expression 'n.a + n.b + count(*)' includes the implicit grouping key 'n.b'. It may be possible to rewrite the query by extracting these grouping/aggregation expressions into a preceding WITH clause. Illegal expression(s): user, media (line 6, column 20 (offset: 349)) " RETURN user {.*, socialMedia: media, activeCategories: collect(category.id) } AS user, categoryCount" ^`

**Comment by Tirokk** [comment]
I haven't researched anything, but anyways …
Why you closed this @Butonix ?
