### ISSUE TITLE
🔧 [Refactor] Webapp: localized enter confirmation code "click on next."

### ISSUE THREAD

**Issue by Elweyn** [Ocelot-Social-Community/Ocelot-Social#6835]
## 🔧 Refactor ticket

On the register process of sender.fm the user gets an email with the registration code that needs to be entered.
If the user uses the link of the email the code is entered automatically! 
But the text under the box says to enter a code. 
It would be optimal to change the text to give the user the instruction to click on the "next"-button.

## 🤖 ToDo
- [ ] Change the localized text so that the user is instructed to click on "next"
  - Line 200 of webapp/locales/de.json: "description": "Öffne Dein E-Mail Postfach und gib den Code ein, den wir geschickt haben.",
  - Line 200 of webapp/locales/en.json: "description": "Open your inbox and enter the code that we've sent to you.",

**Comment by Tirokk** [comment]
This is solved by #6850 I guess? @Elweyn

**Comment by Elweyn** [comment]
Right @Tirokk, fixed by #https://github.com/Ocelot-Social-Community/Ocelot-Social/pull/6850
