### ISSUE TITLE
🐛 [Bug] Backend Unit Tests fail due to expired JWT

### ISSUE THREAD

**Issue by mahula** [Ocelot-Social-Community/Ocelot-Social#6855]
## 🐛 Bugreport
These Backend Unit Tests fail due to an expired JWT (see[ this workflow)](https://github.com/Ocelot-Social-Community/Ocelot-Social/actions/runs/6982636057/job/19002608969)
in  `/backend/src/jwt/decode.spec.ts`

>   ● decode › given valid JWT  › and corresponding user in the database › returns user object without email
>   ● decode › given valid JWT  › and corresponding user in the database › sets lastActiveAt
>   ● decode › given valid JWT *** › and corresponding user in the database › updates lastActiveAt for every authenticated request

### Reason
The token is expired: https://github.com/Ocelot-Social-Community/Ocelot-Social/blob/master/backend/src/jwt/decode.spec.ts#L24

### Suggested solutions
- The quick solution is to renew the token.
- Way better would be to generate a token in the test - else this problem will reoccur

**Comment by Tirokk** [comment]
Found this:
https://verifone.cloud/docs/2checkout/Documentation/07Commerce/2Checkout-ConvertPlus/How-to-generate-a-JSON-Web-Token-JWT
