### ISSUE TITLE
💥 [DevOps] Main Readme – Why it Always Shows that the Tests are Failing?

### ISSUE THREAD

**Issue by Tirokk** [Ocelot-Social-Community/Ocelot-Social#6975]
## 💥 DevOps ticket

Main Readme – Why it always Shows that the Tests are Failing?

<img width="1062" alt="Bildschirmfoto 2024-01-30 um 09 12 52" src="https://github.com/Ocelot-Social-Community/Ocelot-Social/assets/25344101/30bb82c1-ed9a-4ccf-942b-2d3ffe6a9072">

**Comment by mahula** [comment]
The reason is, that the badge relates to an old workflow [ocelot.social test CI ](https://github.com/Ocelot-Social-Community/Ocelot-Social/actions/workflows/test.yml), which doesnot existanymore.
We should connect the badge to the workflows for the master branch.

**Comment by mahula** [comment]
There is no sigle test workflow anymore. We split them up for CI performance reasons.

**Comment by Tirokk** [comment]
> There is no sigle test workflow anymore. We split them up for CI performance reasons.

So lets create a check icon for every singe test then? @mahula 

That would give even more Informations to devs about what we all test then …

**Comment by mahula** [comment]
> So lets create a check icon for every singe test then? @mahula
> 
> That would give even more Informations to devs about what we all test then …

Ok, I will create them.
Then let's see,if that won't be a to badge-crowded Readme.
