### ISSUE TITLE
💥 [DevOps][Backend] Tests Log `faker.name is deprecated since v8.0 and will be removed in V10.0. Please use faker.person`

### ISSUE THREAD

**Issue by Tirokk** [Ocelot-Social-Community/Ocelot-Social#7303]
## 💥 DevOps ticket

Tests Log `faker.name is deprecated since v8.0 and will be removed in V10.0. Please use faker.person`

<img width="1094" alt="Bildschirmfoto 2024-04-22 um 13 08 52" src="https://github.com/Ocelot-Social-Community/Ocelot-Social/assets/25344101/c4eea69b-6923-42d9-9904-214e000932b9">

**Comment by Tirokk** [comment]
Would it be possible to care for this? @Mogge @mahula

**Comment by mahula** [comment]
Sure.

**Comment by mahula** [comment]
> Would it be possible to care for this? @Mogge @mahula

Yes. This has been addressed in #6999
